### PR TITLE
Add e2e onboarding tests

### PR DESCRIPTION
**Pull request by joshuatf**
Adds in e2e tests for the onboarding profiler.

Note that these are just some basic initial tests and this PR does not include all paths and only includes tests for the profiler (not the task list).

### Detailed test instructions:

* `npm ci && composer install && npm run build`
* `npm run docker:up`
* `npm run test:e2e`
* Make sure all tests pass.
* In order to rerun these tests, drop the onboarding data `woocommerce_onboarding_opt_in` and `woocommerce_onboarding_profile`.

### Changelog Note:

Dev: Add e2e onboarding profiler tests.

### CODE REVIEW

**Comment by jeffstieler** [comment]
Looks like this is failing due to errors installing Facebook and Mailchimp. I think we'll need to incorporate the changes from https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1716 in order to resolve.

**Comment by timmyc** [comment]
@joshuatf should this still stay open pending the new e2e testing image?

**Comment by joshuatf** [comment]
@timmyc I think some of the tests here could still be useful.  We're just waiting on https://github.com/woocommerce/woocommerce-admin/pull/4343 to land, right?

/cc @jeffstieler @rrennick

**Comment by rrennick** [comment]
> We're just waiting on #4343 to land, right?

Yes.

**Comment by samueljseay** [comment]
Now that #5028 is merged this could be good to get merged, it just needs a rebase and a move of the file to the new spec directory. I'll give this a go.

**Comment by samueljseay** [comment]
OK I looked closer at this and these tests overlap with the ones shipped in #5028 so I am gonna close this one. If anyone has different feelings please do reopen, but this would likely take significant rework to find anything to test that isn't covered by #5028

**Pull request closed without merging**
