### PR TITLE
Stop using Composer 1.x.

### PR DESCRIPTION
**Pull request by jeffstieler**
Trying to fix the CI test suite, I'm not sure why we have Composer 1.x specified anywhere. 

No changelog.

### CODE REVIEW

**Review by adrianduffell — APPROVED** [review]
Thanks @jeffstieler LGTM 🚀 

Composer 1 was required a while ago to build older WooCommerce versions, 4.7 and under if IIRC. We don't need to test against those versions now.

We could possibly go a step further and remove the ability to set the Composer version and just use what's available in CI out of the box. It would speed up the tests a little as the script wouldn't need to perform multiple Composer updates here:

https://github.com/woocommerce/woocommerce-admin/blob/4bb2fb1a38f7daf25e66f3e71960f88d9aa397e6/bin/ci/gh-install-wp-tests.sh#L126-L130

This looks good to merge as it is though.

**Comment by joshuatf** [comment]
@jeffstieler Do you want to merge this as is or remove the multiple composer version tests mentioned above?

**Comment by moon0326** [comment]
@jeffstieler Hey Jeff ✋ Would you like to merge this? It looks good 👍

**Comment by jeffstieler** [comment]
Hi @moon0326 I was hoping the PHP tests would be passing before merging. I think that will require modifying the test matrix and minimum compatible version of WooCommerce, which I didn't want to impose upon the team.

**Pull request closed without merging**
