### PR TITLE
Localize string

### LINKED ISSUE #6456: Home Screen Welcome modal's last step description translation string isn't registered
**Describe the bug**
A Home Screen Welcome modal's last slide description is not registered as a string available for translations, it's always in English.

You can see here, that no __() function is used for this description: https://github.com/woocommerce/woocommerce-admin/blob/ef6aa388c40abffecb512e1af49c915ebe1449a6/client/homescreen/welcome-modal/index.js#L57

**To Reproduce**

1. Switch WP language to non-en.
2. Go to WooCommerce->Home for the first time after lauching the new Home Screen.
3. Look at the last step of the Welcome modal.

**Screenshots**
Zrzut ekranu 2021-02-26 o 16 08 49

WP 5.6.2
WC 5.0.0
WC Admin 1.9.0. (bundled with WC)

PS Similar bug has been submitted here: #5392 but the date string are still not fixed.

### PR DESCRIPTION
**Pull request by hsingyuc**
Fixes #6456 

This PR is to localize a string but I can't get the WooCommerce-admin translation working, so couldn't test it.

### Detailed test instructions:
-  `npm run i18n lang=xx_YY`  **( But I have an error locally, couldn't run this )**
-  Check PO file for localized string

No changelog required

### CODE REVIEW

**Comment by ilyasfoo** [comment]
For future reference, when running `npm run i18n lang=xx_YY`  I've also had the following error at `packages/number/node_modules/locutus/php/_locutus_shared/_locutus_shared_bc.js: Invalid regular expression flag (6:6)`:

```
  4 |   // eslint-disable-line camelcase
  5 |   //  discuss at: http://locutus.io
> 6 | /php/_helpers/_bc
    |       ^
  7 |   // original by: lmeyrick (https://sourceforge.net/projects/bcmath-js/)
  8 |   // improved by: Brett Zamir (http://brett-zamir.me)
  9 |   //   example 1: var $bc = _bc()
```

I'm not entirely sure why this happening, just noting that when I manually remove the line `/php/_helpers/_bc` it'll let me run.

**Review by ilyasfoo — APPROVED** [review]
Changes look good, thank you for the fix @hsingyuc!

**Comment by ilyasfoo** [comment]
@hsingyuc Can you rebase this fix with the latest `main`? The old JS unit test had an issue that blocks merging.

**Comment by hsingyuc** [comment]
@ilyasfoo  The PR has been rebased!
@adrianduffell  thank you for adding the changelog!

**Comment by adrianduffell** [comment]
@hsingyuc No problems, I didn't know we could commit to your fork until now. 

I thought a changelog would still be helpful for this PR. However, I don't think we can provide testing instructions since the string isn't translated yet.

Merging this now. Thank you!

**Pull request merged**
