### PR TITLE
use summary query to total coupons per order

### LINKED ISSUE #2400: Revenue count and order count are incorrect when 2 or more coupons applied to an order
Description: The gross revenue and order count are not calculated correctly. This happens when more than one coupon is applied to an order. 

To Reproduce:
The following steps assume that WooCommerce and WooCommerce Admin are installed. I am using Stripe Gateway, but any gateway will do. I started with a fresh install.
1. Create a simple product called "widget" with a price of $10.
2. Create a coupon called "oneoff" with a "fixed cart discount" and a value of $1.
3. Create another coupon called "twooff" with a "fixed cart discount" and a value of $2.
4. Add a single "widget" to an empty cart with no coupon added. The cart total is $10. Complete the purchase.
5. Add a single "widget" to an empty cart with one "oneoff" coupon added. The cart total is $9. Complete the purchase.
6. Add a single "widget" to an empty cart with one "oneoff" coupon and one "twooff" coupon added. The cart total is $7. Complete the purchase.
7. Go to WooCommerce -> Orders. The total of the three orders is $26 ($10+$9+$7)
8. Complete all orders.
9. Go to Analytics->Revenue. The gross revenue displays as $33. In the revenue table, it displays 4 orders.
10. Go to Analytics->Orders. The orders count displays as 4. The net revenue displays as $33. In the orders table, it displays 3 orders and the net revenue adds up to $26.

Expected behavior: The gross revenue and net revenue should be $26. The order count should be 3, not 4.

Screenshots: attached

Desktop:
OS: Mac 10.14.5
Browser: Chrome
Version: 74.0.3729.169

WordPress: version 5.2.1
WooCommerce: Version 3.6.4
WooCommerce Admin: Version 0.12.0

Additional context:
The SQL query that gets generated in class-wc-admin-reports-orders-data-store.php looks similar to this:

_SELECT
	SUM( CASE WHEN wp_wc_order_stats.parent_id = 0 THEN 1 ELSE 0 END ) as orders_count, 
	SUM(wp_wc_order_stats.num_items_sold) as num_items_sold, 
	SUM(wp_wc_order_stats.gross_total) AS gross_revenue, 
	SUM(discount_amount) AS coupons, 
	COUNT(DISTINCT coupon_id) as coupons_count, 
	ABS( SUM( CASE WHEN wp_wc_order_stats.gross_total < 0 THEN wp_wc_order_stats.gross_total END ) ) AS refunds,
	SUM(wp_wc_order_stats.tax_total) AS taxes, 
	SUM(wp_wc_order_stats.shipping_total) AS shipping, 
	SUM(wp_wc_order_stats.net_total) AS net_revenue
FROM
	wp_wc_order_stats
LEFT JOIN
	wp_wc_order_coupon_lookup ON wp_wc_order_coupon_lookup.order_id = wp_wc_order_stats.order_id
WHERE
	1=1
AND wp_wc_order_stats.date_created <= '2019-06-10 23:59:59' 
AND wp_wc_order_stats.date_created >= '2019-06-10 00:00:00'
AND ( wp_wc_order_stats.status NOT IN ( 'wc-trash','wc-pending','wc-failed','wc-cancelled' ) )_

I believe the problem exists . in the LEFT JOIN. The way this SQL query is written, the join creates an extra row because there are two records in the wp_wc_order_coupon_lookup table.

### PR DESCRIPTION
**Pull request by rrennick**
Fixes #2400 

This PR implements a coupon summary query grouped by `order_id` to total the coupons per order when retrieving the order stats.

### Detailed test instructions:

- Create these orders in the dashboard
  - One product with quantity of 2 or more, 0 coupons
  - One product with quantity of 2 or more, 1 coupons
  - One product with quantity of 2 or more, 2 coupons
  - Repeat the above 3 with two products
- Pay for all the orders
- Compare both the revenue and orders analytics to the totals (total, net, coupons, & taxes) for the orders
 
### Changelog Note:

Fix: Only calculate one order row when the order has multiple coupons.

### CODE REVIEW

**Comment by timmyc** [comment]
Thanks for grabbing this one @rrennick - looks like there is a failing test that needs to be looked into.

**Comment by rrennick** [comment]
@timmyc This one is ready for re-review.

**Comment by timmyc** [comment]
➕ for some unit tests if possible.

**Comment by rrennick** [comment]
> Can we add a test case to make sure we don't regress on this?

@jeffstieler Thanks for the suggestion. Unit test added.

**Pull request merged**
