### PR TITLE
Fix attribute filter for "any X" variations.

### LINKED ISSUE #6722: Reports in Analytics > Orders don't return variations with "Any X"
When using a variable product with variation attributes set to `Any X`, like so:

Markup on 2021-03-31 at 16:42:27

... Analytics > Orders will not return correct data when you specify an specific attribute:

Markup on 2021-03-31 at 16:42:39

From @joshuatf in Slack:

> Can confirm the issue.  Seems like our filtering looks for specifically set attributes on products, which this type of "any" variation would not contain.

3849522-zen

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #6722.

This PR seeks to fix the "any X" variation case by using the order item meta table for attribute filtering rather than the post meta table.

### Detailed test instructions:

- Create a variable product with variation attributes set to `Any X`, like so:

Markup on 2021-03-31 at 16:42:27

- Place order(s) for that variation
- Verify that you can filter for the "any X" attribute using the attribute filter:

Markup on 2021-03-31 at 16:42:39

### CODE REVIEW

**Comment by samueljseay** [comment]
I've been trying to test this, but for some reason when I search for the attribute to select for "is", nothing turns up, I'm not sure if its filtering already fetched data or supposed to fetch some data when typing in that box, but nothing appears for me. I have checked my setup a few times, and I have orders, but even if I didn't have orders I expect this search should at least work in the filters section.

Screenshot 2021-06-01 at 1 39 51 PM


variation:

Screenshot 2021-06-01 at 1 43 17 PM


attributes:

Screenshot 2021-06-01 at 1 48 36 PM

**Comment by jeffstieler** [comment]
Nice catch @samueljseay - the query for custom attribute terms is still broken in the "any X" case.

**Comment by samueljseay** [comment]
@jeffstieler I'm not clear exactly on what you mean. I thought that in my testing I had replicated your test steps exactly. Is the PR issue fixed and what I've found is a separate bug or is there an issue with the solution here?

**Comment by jeffstieler** [comment]
@samueljseay the solution here is not complete.

**Comment by jeffstieler** [comment]
@samueljseay I've fixed the query for custom attribute terms in 3caeb8f. This is ready for another review.

**Comment by jeffstieler** [comment]
In 0cfd785, I fixed a bug where custom attributes that were defined across several products were missing terms (only terms on one product would show up).

**Review by louwie17 — APPROVED** [review]
Some of the code was a little over my head, but overall things looked good and tested well @jeffstieler 👍 Also thanks for adding tests.

**Pull request merged**
