### PR TITLE
Update Jest@26.6.3,

### PR DESCRIPTION
**Pull request by tomalec**
I started this with a hope to address `window`/`jsdom` problems encountered in https://github.com/woocommerce/woocommerce-admin/pull/7378#issuecomment-885870676
Also, this PR may help with https://github.com/woocommerce/woocommerce-admin/issues/7218#issuecomment-867250468

- Update `jest@26.6.3` (from `24.9.0`), remove `jest-environment-jsdom-sixteen`, to somewhat reduce our technical debt.
- Set timers to `legacy` as that is what was actually used before. AFAIK `jest-environment-jsdom-sixteen` was hardcoding it as legacy regardless of config.
- Update the usage of fake timers
- Update snapshot of the `<Leaderboard>` component - I have no idea how and why it passed before. See [below](https://github.com/woocommerce/woocommerce-admin/pull/7418#issuecomment-886796457).

### Accessibility

n/a this PR affects only dev tooling, and updates existing dependencies.

### Detailed test instructions:

1. `npm run test`

----

no changelog needed - this changes only dev tooling
<!--- Please add a Changelog note

Enter a changelog note using the following CLI command `npm run changelogger -- add` and commit changes.

### CODE REVIEW

**Comment by tomalec** [comment]
There is one failing test:
```log
  ● Leaderboard › should render empty message when there are no rows

    expect(received).toMatchSnapshot()

    Snapshot name: `Leaderboard should render empty message when there are no rows 1`

    - Snapshot  - 1
    + Received  + 0

    @@ -13,11 +13,10 @@
          <div
            class="components-card__body css-xmjzce-BodyUI e1q7k77g3"
          >
            <div
              class="woocommerce-table is-empty"
    -         style="--number-of-rows: 5;"

```

But, AFAI Can Tell it should fail, as there is no reason why `<EmptyTable>` should have 5 rows. There is no such prop being passed:
https://github.com/woocommerce/woocommerce-admin/blob/main/client/analytics/components/leaderboard/index.js#L80


I have no idea how and why this test passed before.

**Comment by tomalec** [comment]
BTW, I don't know why we use `toMatchSnapshot` everywhere, instead of actually testing what the test description states. It breaks test atomicity, making them extremely fragile and hard to maintain.

IMO, we should write something like:
```js
test( 'should render empty message when there are no rows', () => {
	  // ...
	  
	  expect( leaderboard ).to.contain( 'EmptyTable' )
	  expect( leaderboard ).to.have.rendered.text( 'No data recorded for the selected time period' );
} );
```

**Comment by louwie17** [comment]
@tomalec just a heads up in relation to this PR (given it is still in draft). The reason we are still using `24.9` is because of a pretty big performance issue in newer versions of Jest. See [this original PR](https://github.com/woocommerce/woocommerce-admin/pull/4942) and this [Jest issue](https://github.com/facebook/jest/issues/9457) which is still open 😢 

If you do go ahead with this, it would be great to get some info on the performance difference, is it still relevant or not? (We might even want to try Jest 27 now).

**Comment by samueljseay** [comment]
@tomalec @louwie17 I tried jest 27 lately its a lot faster, but I had trouble getting some tests working. 

@tomalec Also I'm happy to delete the failing snapshot test. I encouraged the team to stop writing snapshot tests because of what you say which is they're basically useless for testing anything. If its possible to write a corresponding basic test for the removed snapshot one then great, but I wouldn't block on that either.

**Comment by tomalec** [comment]
Thanks for all the info :) Given my local env problems related to https://github.com/woocommerce/woocommerce-admin/pull/7378 are now solved (`react-test-renderer` + `node@14`) I'll try to jump to a higher version that does not degrade the performance. Hopefully by the end of this week / some time off next week.

**Comment by psealock** [comment]
I'll close this in favor of https://github.com/woocommerce/woocommerce-admin/pull/7430 which update to version 27. Thank you @tomalec for getting this effort underway!

**Pull request closed without merging**
