### PR TITLE
Onboarding: Add purchase products task list item

### LINKED ISSUE #3442: Onboarding - Add "Purchase and install extensions" task
Blocked by #3441.

If the user decide to purchase extensions later,  a "purchase and install extensions" task should be added to the task list. This task should display first in the list.

Screen Shot 2019-12-17 at 11 04 20 AM

The task should also show the modal added in #3441 before redirecting -- reminding the user about their previous product selection. Confirming they want to continue will send them to WooCommerce.com's in-app purchase flow.

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #3442

* Adds a task list item for purchasing after the profiler.
* Adds the cart modal to the task list page.
* Removes already installed items from the cart.

### Screenshots
Screen Shot 2019-12-24 at 8 23 24 PM
Screen Shot 2019-12-24 at 7 55 17 PM

### Detailed test instructions:

1. Install at least one plugin from the product types.
2. Run through the profiler, selecting product types and/or a theme that requires purchase.
3. Make sure the cart modal at the end of the theme selection continues to work as expected.
4. Make sure the cart includes items that require purchase, but not already installed plugins.
5. Continue to the task list without purchasing.
6. Note a task list item exists for purchasing items.
7.  Finish purchase and/or install the necessary plugins required.
8. Make sure the task list item is shown as completed and clicking the completed task list item does not open the cart modal.

Question: Do we want to show this task list item as complete or just hide it after complete (as it is now).

### CODE REVIEW

**Comment by psealock** [comment]
Is the WooCommerce.com's in-app purchase flow supposed to return you to the task list? I get stuck on the checkout confirmation screen on WCCOM.

**Comment by psealock** [comment]
>Question: Do we want to show this task list item as complete or just hide it after complete (as it is now).

I'd say show it as complete. Its always nice to have reminder of completed tasks.

**Comment by timmyc** [comment]
I got the same outcome as Paul, but am guessing it was due to testing on a local site that isn't "connected" to wccom?

**Comment by joshuatf** [comment]
>I got the same outcome as Paul, but am guessing it was due to testing on a local site that isn't "connected" to wccom?

I believe this is correct.  I've only been able to get this to redirect on a site that has a public facing URL.

/cc @timmyc @psealock 

>Question: Do we want to show this task list item as complete or just hide it after complete (as it is now).
I'd say show it as complete. Its always nice to have reminder of completed tasks.

I like this idea as well.  @jameskoster @pmcpinto do you want to weigh in?

**Comment by pmcpinto** [comment]
I agree that it makes sense to keep the task as completed, it can be helpful for the users to have that reassurance.

**Comment by timmyc** [comment]
Excellent, I think this is good to go once we have the item remain in the task list and marked as done once completed. I'll run a full test end-to-end once that is ready on a public/connected site to confirm it works as expected.

**Comment by joshuatf** [comment]
@timmyc @psealock This one has been rebased and updated to show the task item even when complete.

Updating testing instructions above to reflect the updates.

**Comment by rrennick** [comment]
@joshuatf There's a merge conflict on this one.

**Comment by joshuatf** [comment]
>One oddity, not sure if is expected or not, but I was redirected to the wp-admin plugins page after doing the WooCommerce connect + extension install process:

Good catch on this @timmyc.  I think normally that's expected behavior, but looking at the onboarding flow it looks like this should dump us back into the dashboard (task list) when this is complete via the `wccom-back` parameter.  Brought up this issue in Slack to see if there has been any previous discussion around it.

**Pull request merged**
