### PR TITLE
Render SummaryNumber delta precisely.

### PR DESCRIPTION
**Pull request by tomalec**
Previously only a given delta was rendered as an integer. Now it renders the number with a given precision.
Fixes https://github.com/woocommerce/woocommerce-admin/issues/5925.

### Accessibility

I didn't add any new interactions

-   [x] I've tested using only a keyboard (no mouse)
-   [ ] I've tested using a screen reader
-   [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
-   [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Detailed test instructions:

1. Create an instance of `<SummaryNumber>` with `delta=10.12`, 
    ```js
    <SummaryNumber
		label={ "Net Sales" }
		value={ "$24.00" }
		delta={ 10.12 }
	/>
    ```
2. Check how it's rendered.

Or 
1. Build storybook `npm run storybook`
2. Open [`SummaryList` demo](http://localhost:6007/?path=/story/woocommerce-admin-components-summarylist--basic)
3. Check how the number is rendered.

image

## Risks:
There may be places that rely on the previous behavior to format the number. Expecting `<SummaryNumber delta={ 10.0000000001 }/>` to render only `10%`.
After this change may get unexpected results. However, this behavior was not documented before, so I'd consider it was risky in the first place to rely on undocumented side-effects.

## Addtitional comments:
Previously it was truncating the number, not rounding it, which I find misleading from the user perspective.

### CODE REVIEW

**Review by becdetat — DISMISSED** [review]
This works well in storybook and the code looks good. I'm a bit concerned about the line endings changes in readme.txt, we've had a few problems with normalising them. Can you unstage the extra lines?

**Comment by tomalec** [comment]
Ah, sorry, that was probably a result of running Github's merge on a Windows machine. I'll fix that.

**Comment by tomalec** [comment]
Ah, sorry. Fixed.

**Review by becdetat — APPROVED** [review]
Looks great 👍

**Comment by tomalec** [comment]
Failing Travis seems to be an issue with `main` branch, as it was passing 13hrs ago before 9b28b479a4a832ba9f2b87178540d4abbea9f539.

**Comment by tomalec** [comment]
I can revert the recent `main -> fix/5925-summarynumber-float` merge, and change the `readme.txt` entry in a way it will not be conflicting, to make the checks green.

**Comment by becdetat** [comment]
I can't reproduce the failure locally. It _looks_ like some version dependency didn't install properly.

I'll try pushing an empty commit just to see if it was a transient error.

**Comment by becdetat** [comment]
Not a transient error. I've asked for a second opinion here: p1611109900091100-slack-C9K5T0XSP

**Comment by becdetat** [comment]
@tomalec it looks like this is indeed a problem with the latest `main` - everything has started failing, probably related to something in WooCommerce 4.9.1.

> I can revert the recent main -> fix/5925-summarynumber-float merge, and change the readme.txt entry in a way it will not be conflicting, to make the checks green.

If you can give that a try it would be great :-)

**Comment by tomalec** [comment]
> I'll try pushing an empty commit just to see if it was a transient error.

I think there is no need for that. You can click "Restart build" on the right side at https://travis-ci.com/github/woocommerce/woocommerce-admin/builds/213731255 (once you're logged in with GitHub)

**Comment by tomalec** [comment]
Now, it's not possible to merge `main` to this branch due to https://github.com/woocommerce/woocommerce-admin/issues/6133

**Comment by tomalec** [comment]
I'm merging it with `--no-verify` as the errors have nothing to do with the changes from this PR.

**Comment by becdetat** [comment]
Nice, thanks for this @tomalec

**Pull request merged**
