### PR TITLE
Remove stylesheets supporting IE11

### PR DESCRIPTION
**Pull request by samueljseay**
This is the last of the support code that supports IE11 in wc-admin client and `@woocommerce/components`

I'm removing these because we no longer support IE11 due to Wordpress dropping support.

### CODE REVIEW

**Comment by ilyasfoo** [comment]
According to https://wooengineering.wordpress.com/2021/05/14/ie11-support-in-woocommerce-products-while-its-being-phased-out-from-wordpress/#comment-109, core is dropping support starting from `5.6`. If that's correct, I'd hold merging this to main until 11th June.

**Comment by ilyasfoo** [comment]
According to pcShBQ-2a-p2#comment-109, core is dropping IE support starting from version `5.6`. If that's correct, I'd hold merging this to main until 11th June.

**Comment by samueljseay** [comment]
@ilyasfoo if you read it closely you'll see the plan is to drop no later than July. See bullet point #1. Also recently merged: https://github.com/woocommerce/woocommerce-admin/pull/7112

**Comment by adrianduffell** [comment]
I think we can merge this according to the public announcement 🎉 

> IE11 support will be selectively removed in the versions after WooCommerce 5.4, and users can expect support for IE11 to be fully dropped by WooCommerce 5.6, which is scheduled for release on August 10th.

 https://developer.woocommerce.com/2021/05/24/developer-advisory-plan-to-remove-ie-11-support-in-woocommerce/

**Review by ilyasfoo — APPROVED** [review]
Good points, I agree we can merge 🚢

**Comment by jeffstieler** [comment]
This missed some IE script references @samueljseay - like: https://github.com/woocommerce/woocommerce-admin/blob/6468742c6e1df872ad99e907dfbe67473d52e2b1/src/Loader.php#L696-L705

**Pull request merged**
