### PR TITLE
Present Inbox notes in a panel with header

### LINKED ISSUE #7242: Present Inbox notes in a panel with "Inbox" header

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #7242

This PR adds the Inbox notes into `Card` component with some CSS changes to reflect the new design shown in the issue.

This PR also includes changes for https://github.com/woocommerce/woocommerce-admin/issues/7246

This PR does not include the following changes. 

1. Icons 
2. Unread state
3. Dismiss all from the ellipsis menu
4. ~Clicking `dismiss` still shows a popup menu~  https://github.com/woocommerce/woocommerce-admin/pull/7868 has been merged

### Screenshots
Screen Shot 2021-10-28 at 4 39 13 PM

### Detailed test instructions:

1. Clone this branch
2. Navigate to WooCommerce -> Home
3. Confirm the new design

### CODE REVIEW

**Comment by moon0326** [comment]
> It seems some CSS conflict is happening. I suspect WCPay plugin is causing this since it disappears when I deactivate it. I think it's the CSS in `experimental` package, I'm not sure if we use dependency extraction for this? 🤔
> 
> image

Thank you for catching it. I'll look into it 👍

**Comment by moon0326** [comment]
@ilyasfoo Updated CSS in https://github.com/woocommerce/woocommerce-admin/pull/7864/commits/84ca523d14dcf740dfa83181c161c2215e73f133

**Review by adrianduffell — CHANGES_REQUESTED** [review]
Nice work on this @moon0326, this is shaping up great  🎉 

I confirmed it's working well with WCPay plugin active.

Just a couple of minor things before I think this is ready to merge:

- Is the`package-lock.json` change needed?
- I think we might need a changelog added for `packages/experimental`.

**Comment by moon0326** [comment]
> Nice work on this @moon0326, this is shaping up great 🎉
> 
> I confirmed it's working well with WCPay plugin active.
> 
> Just a couple of minor things before I think this is ready to merge:
> 
> * Is the`package-lock.json` change needed?
> * I think we might need a changelog added for `packages/experimental`.

Thank you @adrianduffell 

Updated both of them in https://github.com/woocommerce/woocommerce-admin/pull/7864/commits/7544b13b2f2baec1b038c44db305e72122b66c48 and https://github.com/woocommerce/woocommerce-admin/pull/7864/commits/2a5ee8426b2776c521541125be0a28cb325cd794

**Review by adrianduffell — APPROVED** [review]

**Comment by adrianduffell** [comment]
@moon0326 LGTM thanks for those changes 🚀

**Pull request merged**
