### PR TITLE
Import @wordpress/base-styles/default-custom-properties to get --wp-admin-theme-color

### LINKED ISSUE #5449: Icon issue in Recommended Coupon Extensions
**Describe the bug**
After activating WooCommerce Admin, the icons in the Recommended Coupons Extensions look different from before and not showing up correctly on hover.

**To Reproduce**

1. Have WooCommerce activated and WooCommerce Admin **deactivated**.
2. Go to http://example.test/wp-admin/edit.php?post_type=shop_coupon
3. Take note of the icons and their hover state in the Recommended Coupon Extensions section. The icons have borders and they have blue background in hover state.
4. Activate WooCommerce Admin plugin.
5. Go to http://example.test/wp-admin/edit.php?post_type=shop_coupon
6. The icons do not have borders. When you hover over the items, the icons disappear.

**Expected behavior**
At least icons should not disappear on hover.

**Screenshots**

Before activating WooCommerce Admin (the Personalized Coupons is in hover state): 

Screenshot on 2020-10-21 at 18-39-00

After activating WooCommerce Admin (icon disappear on hover): 

Screenshot on 2020-10-21 at 18-42-12

**Desktop (please complete the following information):**

* OS: Mac OS
* Browser [e.g. chrome, safari]: FireFox
* Version [e.g. 22]: 81

**Additional context**

The site is create using Valet+, with fresh new `git clone` of WooCommerce and WooCommerce Admin.

### PR DESCRIPTION
**Pull request by ecgan**
This is to get the root admin scheme color, so that we can use `--wp-admin-theme-color` in CSS.

Fixes #5449. Specifically, see [this comment](https://github.com/woocommerce/woocommerce-admin/issues/5449#issuecomment-718051052) for the root cause of the issue.

### Accessibility

Not applicable.

### Screenshots

The icons should show up correctly like below:

Screenshot on 2020-10-29 at 00-40-39

### Detailed test instructions:

- Make sure your WooCommerce-Admin package has a higher version number than the WooCommerce package.
- Checkout the code, run `npm install` and `npm run build`.
- Visit the coupon page: https://example.test/wp-admin/edit.php?post_type=shop_coupon
- Make sure the icons shows up okay when you hover over them, as shown in the screenshot above.
- Open up dev tools and make sure that you have this file loaded:

Screenshot on 2020-10-29 at 00-45-59

- Open up the file in a new tab, use the search command with the keyword ":root" and make sure you see the following code exists in the file (https://example.test/wp-content/plugins/woocommerce-admin/dist/marketing-coupons/style.css?ver=1602685252): 

```css
:root{--wp-admin-theme-color:#007cba;--wp-admin-theme-color-darker-10:#006ba1;--wp-admin-theme-color-darker-20:#005a87}
```

### Changelog Note:

Fix: Import @wordpress/base-styles/default-custom-properties in CSS file, so that we can use --wp-admin-theme-color in CSS.

### CODE REVIEW

**Review by samueljseay — APPROVED** [review]
Thank you for this fix! 🚢

**Comment by samueljseay** [comment]
I'll try fix up the build on this one, we've been having some travis issues.

**Comment by samueljseay** [comment]
Once https://github.com/woocommerce/woocommerce-admin/pull/5504 is merged we should be able to remerge master to this branch to pass the build :)

**Comment by samueljseay** [comment]
Thanks again for this fix @ecgan

**Comment by ecgan** [comment]
@samueljseay , no problem, and thanks for helping to merge this PR 🙂

**Pull request merged**
