### PR TITLE
Handle custom currency formats

### PR DESCRIPTION
**Pull request by psealock**
Fixes https://github.com/woocommerce/woocommerce-admin/issues/2893

cc @KZeni 

Many extensions use the `woocommerce_price_format` filter to change the way WooCommerce renders currencies. More often than not, its to add a currency code and a `span` tag. Unfortunately, this renders poorly in wc-admin:

Screen Shot 2019-12-04 at 8 41 01 AM

In order to avoid using [dangerouslySetInnerHtml](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml), two changes are proposed in this PR.

## Strip tags from currency formats

If we remove html tags from the format strings, the result should be appropriate in the majority of cases. Styles provided by extensions wouldn't apply, but at least its readable.

Screen Shot 2019-12-04 at 8 39 57 AM

### Test stripping tags

1. At the bottom of `woocommerce-admin.php` paste this code to simulate an extension modifying currency formats:

```php
function amperageAddPriceSuffix( $format, $currency_pos ) {
	$currency = get_woocommerce_currency();
	$format   = '%1$s%2$s <span class="woocommerce-Price-currencyFormat">' . $currency . '</span>';
	return $format;
}
add_action( 'woocommerce_price_format', 'amperageAddPriceSuffix', 1, 2 );
```
2. View reports and see the currency formats updated.

### CODE REVIEW

**Comment by jeffstieler** [comment]
Were we wanting to address this? The [original issue](https://github.com/woocommerce/woocommerce-admin/issues/2893) was closed. cc: @timmyc

**Comment by timmyc** [comment]
Let's chat about this one in the hangout tomorrow.

**Comment by joshuatf** [comment]
@psealock @timmyc What was the verdict on this one from the hangout?  Does this need another review?

**Comment by psealock** [comment]
@joshuatf The verdict was to keep the part that strips tags, but remove the ability to provide a custom component.

The testing instructions and original description have been updated and this could use a look. Thanks.

**Comment by rrennick** [comment]
@psealock package-lock.json snuck into this one.

**Comment by psealock** [comment]
Thanks @rrennick, I reverted package-lock back to whats on master.

**Pull request merged**
