### PR TITLE
Fix/7660 Remove note->read_meta

### LINKED ISSUE #7660: Note is attempting to query for meta against wp_postmeta table, but it is not a post
### Describe the bug
When a`Note` is loaded, it attempts to load the metadata of the note ([source](https://github.com/woocommerce/woocommerce-admin/blob/9a008e204683e80de00324ff55676e496e76849b/src/Notes/DataStore.php#L116)), however, a Note is not a post, it uses a custom table. Note meta should live in a separate custom table, that doesn't seem to exist - assuming that means notes have no meta... but definitely should not be querying the postmeta table for meta.

```
WC_Data_Store_WP->read_meta()
wp-content/plugins/woocommerce/includes/data-stores/class-wc-data-store-wp.php:94
WC_Data_Store->__call()
wp-content/plugins/woocommerce/includes/class-wc-data-store.php:207
WC_Data->read_meta_data()
wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php:598
Automattic\W\A\N\DataStore->read()
wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/DataStore.php:116
WC_Data_Store->read()
wp-content/plugins/woocommerce/includes/class-wc-data-store.php:159
Automattic\W\A\N\Note->__construct()
wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/Note.php:89
WC_Notes_Run_Db_Update::show_reminder()
wp-content/plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php:278
do_action('current_screen')
wp-includes/plugin.php:470
WP_Screen->set_current_screen()
wp-admin/includes/class-wp-screen.php:421
set_current_screen()
wp-admin/includes/screen.php:243
```

### To Reproduce
To reproduce I had to force a note to attempt to be displayed, I did this by simply calling `WC_Notes_Run_Db_Update::show_reminder();` and in doing so it would attempt to load the notes DB update reminder.

You can then see by using Query Monitor or your preferred alternative that a query is being made against the postmeta table, looking for meta using the ID of the note named `wc-update-db-reminder`.

### Screenshots
https://c.m6e.io/w2VDQe

### Expected behavior
I would not expect non post objects to call the default WP postmeta table for metadata.

### Additional context
Tested using the latest stable WooCommerce 5.6.0 which includes WooCommerce Admin 2.5.1.

### PR DESCRIPTION
**Pull request by johnregan3**
Fixes #7660 

Removes calls to `read_meta_data()` in the Notes DataStore as they are not used.

### CODE REVIEW

**Comment by mattsherman** [comment]
@woocommerce/mothra Let's get some 👀 on this!

**Review by louwie17 — COMMENTED** [review]
Hi @johnregan3,
Thanks for fixing this, it is much appreciated :)
This tests well and changes look good, although I think we could also remove the `save_meta_data` calls [here](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Notes/DataStore.php#L175) and on line 46 as well, if you don't mind, that way there won't be any confusion.

**Comment by johnregan3** [comment]
@louwie17  Updated.  Thanks!

**Review by louwie17 — APPROVED** [review]
Thanks for the updates @johnregan3, these changes look good, feel free to merge this whenever you are able to.
We appreciate your contributions 😄

**Comment by johnregan3** [comment]
@louwie17  Thank you for the kind words, and I'm glad to be of help.  

Apologies, but I'm not familiar with precisely how things are done in this repo.  I see your approval above, but I'm also seeing "5 workflows awaiting approval" which appears to be all tests.  Finally, I see "This pull request can be automatically merge by project collaborators. [only those with write access to this repository can merge pull requests]"  

Can you advise on what I need to do next?  Thanks!

**Comment by louwie17** [comment]
> Apologies, but I'm not familiar with precisely how things are done in this repo. I see your approval above, but I'm also seeing "5 workflows awaiting approval" which appears to be all tests. Finally, I see "This pull request can be automatically merge by project collaborators. [only those with write access to this repository can merge pull requests]"
> 
> Can you advise on what I need to do next? Thanks!

@johnregan3 thanks I didn't look at that to closely, I had to approve the workflows to run given it was your first contribution. This might be the same case for merging the PR, I can merge it once the workflows finish running and succeed.
I believe for any future contributions you could merge it yourself once it has been approved.

**Pull request merged**
