### PR TITLE
release 0.15.0

### PR DESCRIPTION
**Pull request by psealock**
Changes for release `0.15.0`

### CODE REVIEW

**Comment by jeffstieler** [comment]
https://github.com/woocommerce/woocommerce-admin/pull/2637

**Comment by psealock** [comment]
>lets pause on the merge.

I'll merge this and not publish the release. A new `0.15.1` will be created anyways.

**Comment by jeffstieler** [comment]
> I'll merge this and not publish the release. A new 0.15.1 will be created anyways.

Why would we create a `0.15.1` when we haven't released a `0.15.0` to .org?

**Comment by psealock** [comment]
>Why would we create a 0.15.1 when we haven't released a 0.15.0 to .org?

Yep, good point. I'll delete the current 0.15.0 tag and start over.

**Comment by psealock** [comment]
Closing this one out for a fresh cut off master since no PRs have been merged in the current sprint.

**Pull request closed without merging**
