### PR TITLE
Revert "Revert "Update to new Snackbar component and notice store""

### PR DESCRIPTION
**Pull request by psealock**
Fixes https://github.com/woocommerce/woocommerce-admin/issues/2203

Reverts woocommerce/woocommerce-admin#2634

This PR reverts the revert to re-implement Snackbar and transient notices changes originally made in https://github.com/woocommerce/woocommerce-admin/pull/2596.

The revert was done to due to dependencies on React version 16.8. This may be a simple issue of bumping WP dependency to `5.2.0`. Alternatively, we may decide to close this PR and stick with React version 16.6.3 found in WP `5.1.1`.

More information in p90Yrv-187

### CODE REVIEW

**Comment by psealock** [comment]
Changing this to Blocked until we can resolve the plan around the dependency issue.

**Comment by psealock** [comment]
@joshuatf We're going ahead and bumping our WP dependency to 5.2, which means we'll go ahead with these changes, see p7bje6-1pI. 

Can you take this one over and rebase to update against master?

**Comment by joshuatf** [comment]
This has been rebased and WP version bumped to 5.2.  Ready for a review.

**Comment by nerrad** [comment]
Looks like there's some plugin header fields that could be added here as well in `woocommerce-admin.php`, namely `Requires at least:` and `Requires PHP:` (see [here](https://developer.wordpress.org/plugins/plugin-basics/header-requirements/#header-fields))

**Comment by psealock** [comment]
This will fix https://github.com/woocommerce/woocommerce-admin/issues/2203

**Comment by joshuatf** [comment]
Thanks for catching that @nerrad!  Updated in https://github.com/woocommerce/woocommerce-admin/pull/2643/commits/04caa182660cf594096cd25c39bbebb0cdf936be

@psealock I also noticed that we list the required resource not only in the main plugin class file, but also in `readme.txt`.  Wondering if this header information is read somewhere else or if we need both.

**Comment by psealock** [comment]
>Wondering if this header information is read somewhere else or if we need both.

Looks like we should have both, https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/

**Pull request merged**
