### PR TITLE
Update README.md spelling

### PR DESCRIPTION
**Pull request by johndcoy**
Corrected WordPress spelling.

Fixes #

_Replace this with a good description of your changes & reasoning._

### Accessibility

-   [ ] I've tested using only a keyboard (no mouse)
-   [ ] I've tested using a screen reader
-   [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
-   [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Detailed test instructions:

-   Ex: Open page `url`
-   Click XYZ…

### CODE REVIEW

**Review by psealock — APPROVED** [review]
Thanks @johndcoy

**Comment by adrianduffell** [comment]
Hi @johndcoy,

I am unable to merge this yet because the build check fails on the PR. It looks like this is because your fork is older and missing some recent changes. I think if you [sync your fork](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) and rebase your branch with `main`, then the build should pass and allow the merge. 

Sorry for the extra work 😞 Thanks!

**Comment by johndcoy** [comment]
Thanks, @adrianduffell! 

I tried using the browser for the first time, last time. :D I've merged main with this branch.

**Comment by adrianduffell** [comment]
Thanks @johndcoy !

**Pull request merged**
