### PR TITLE
Add `navigation.getIdsSetFromQuery` util.

### PR DESCRIPTION
**Pull request by tomalec**
_(this is a follow-up from https://github.com/woocommerce/woocommerce-admin/pull/7028)_

To reduce the overhead of interim array when consumers of `getIdsFromQuery` need set anyway.

As proposed in https://github.com/woocommerce/woocommerce-admin/pull/7028#issuecomment-846066491.

### Accessibility

-   [n/a] I've tested using only a keyboard (no mouse)
-   [n/a] I've tested using a screen reader
-   [n/a] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
-   [n/a] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Detailed test instructions:

-   Run `npm run test`
- Call `getIdsSetFromQuery( '77,,8,foo,null,9' )`

### Additional notes:

1. Personally, I'd make the original `getIdsFromQuery` deprecated, as :
	- "Array of unique" elements without any specific order, is a set anyway.
	- I don't see much value in util that cast another util to an array.
	- `[...~]` is an easy thing to do on the consumer end, if somebody needs an array on their end.
2. @adrianduffell proposed:
	>  I would maybe just change the name of the function to `getIdsFromQueryAsSet`.
	
	Personally, I find it misleading. 
	- Both functions effectively return a set already: the new function returns a set, then the old returns "newFunction as Array". So it's more like `x()` and `xAsArray()`.
	- If I'd be a user of a `foo()`, and I need to cast it to a specific `Type/Set/Array`, I'd rather do `Type(foo())` than expect `fooAsType()`.
	- In a perfect world, without backward-compatibility issues, I'd remove the old function totally, and call the new one `getIdsFromQuery`. Since the most, we can do is deprecate the old `getIdsFromQuery`, and hope someday we could remove it. Then once we would remove it, having `getIdsFromQueryAsSet` **without** `getIdsFromQuery` would be more confusing than having only `getIdsSetFromQuery`.
3. I added a changelog as suggested in PR template via `npm run changelogger -- add`, but got the _"needs changelog entry"_ label from gitbot. Do I need to add it elsewhere as well?

-----

No changelog

### CODE REVIEW

**Review by adrianduffell — CHANGES_REQUESTED** [review]
@tomalec Thanks, this is testing well.

I’m happy to concede the name I proposed. I was just concerned `getIdsSetFromQuery` might be hard to understand because the word "Set" is commonly a verb in function names. This is just a nitpick though. It's not worth holding up the PR if there isn't a better name.

I don't think we need a main changelog entry for the PR as WC Admin doesn't change. Instead, the entry can be added by hand to the changelog in the navigation package. You can override the changelog lint in these instances by adding "No changelog" to a new line in the PR description.

Thanks for adding the tests!

**Comment by tomalec** [comment]
>  I was just concerned getIdsSetFromQuery might be hard to understand because the word "Set" is commonly a verb in function names.

Ah, I didn't think about that. Would `getSetOfIdsFromQuery` sound any better to you? Id does not have the problems I mentioned in OP, "set of" hopefully suggest more of a noun than "set from". I still don't think it's perfect as `getSet…` looks like a typo while writing getter/setter.

**Comment by tomalec** [comment]
I tried merging `main` but still have no idea why PHP unit tests fails for this PR https://github.com/woocommerce/woocommerce-admin/pull/7341/checks?check_run_id=3066206175

**Comment by adrianduffell** [comment]
> > I was just concerned getIdsSetFromQuery might be hard to understand because the word "Set" is commonly a verb in function names.
> 
> Ah, good point, I didn't think about that. Would `getSetOfIdsFromQuery` sound any better to you? Id does not have the problems I mentioned in OP, "set of" hopefully suggests more of a noun than "set from". I still don't think it's perfect as `getSet…` looks like a typo while writing getter/setter.

@tomalec Apologies I didn't see your reply earlier. Yeah `getSetOfIdsFromQuery` works for me better! I agree it's not perfect but is probably a good compromise all things considered.

> I tried merging main but still have no idea why PHP unit tests fails for this PR

Don't worry about this failing unit test, it's a known issue on our end we're working on 😅

It is not a "required" check so you'll still be able to merge the PR.

**Comment by tomalec** [comment]
Thanks @adrianduffell, I renamed the function, merged the latest `main`. The PR is ready for another review.

**Review by adrianduffell — APPROVED** [review]
@tomalec This tested out great and code looks good! Thanks for making the changes.

I think this is ready to merge 🚀

**Pull request merged**
