### PR TITLE
Add missing prompts to installed extensions

### LINKED ISSUE #4056: Marketing tab: missing prompt to continue Google Ads setup
**Describe the bug**
In the marketing tab is missing the prompt the finish the Google Ads setup, when the user has the plugin installed: https://d.pr/i/kZWpKZ

**To Reproduce**
1. Start the new onboarding
2. Install Google Ads in the Business details step
3. Visit the Marketing tab
4. See that's missing the prompt to continue the setup

### PR DESCRIPTION
**Pull request by jconroy**
Fixes #4056

We are adding support for more extensions than I'd originally thought to the MVP - miss understanding on my part.

Adds...
* AutomateWoo
* Google Ads For WooCommerce
* Hubspot for WooCommerce
* Amazon and eBay Integration for WooCommerce 

### Screenshots

Screen Shot 2020-04-04 at 11 47 16 am

### Detailed test instructions:

* On your test site make sure you don't have any of the 4 plugins installed/activated
* Go to Marketing Hub page and see recommended extensions card populated.
* Make your way through installing each plugin see that is removed from recommended once installed then appears under "Installed Extensions" (and needs to be configured)
* For bonus points go through the "Configuration steps" offered by the plugins (AW doesn't have a configuration step) and confirm that the Installed Extensions updates to reflect the correct status once configured.

Note - the hubspot integration is yet to be made available on WCCOM so it will still appear recommended due to placeholder information needing to be updated (which will be done)

### CODE REVIEW

**Comment by danielbitzer** [comment]
Code looks good and all works as expected 👍 

I replaced the some of the SVGs that were actually embedded bitmaps rather than vectors graphics. This reduced file sizes and fixes blurry appearance in some browsers. 
I also updated Hubspot colors to reflect their [brand guidelines](https://www.hubspot.com/style-guide).

**Comment by timmyc** [comment]
@jconroy just wanted to confirm that this should go out in 1.1 final / 4.1 core?

**Comment by jconroy** [comment]
@timmyc yep I believe that is the plan based on https://github.com/woocommerce/woocommerce-admin/issues/4056

**Comment by timmyc** [comment]
@jconroy thanks - is it okay for me to merge this now and cherrypick into the 1.1 release then?

**Comment by jconroy** [comment]
@timmyc yep I think so, sorry for the delay, too many balls in the air atm

**Pull request merged**
