### PR TITLE
Fix in app purchase back link for recommend marketing extensions card

### LINKED ISSUE #4294: Marketing Tab In app purchase back URL not working for subdirectory installs
The `wccom-back` param being passed when you click through to an extension does not appear to be handling if your WP install is in a subdirectory properly.

**Example**

Have a subdirectory site setup at `https://thisisnotarealdomain.foo/spang/`

The link to go and buy/install automatewoo includes `&wccom-back=%2Fwp-admin%2Fadmin.php%3Fpage%3Dwc-admin%26path%3D%252Fmarketing`

But it is missing the encoded `/spang/`.

### PR DESCRIPTION
**Pull request by danielbitzer**
Fixes #4294 

If WordPress is installed in a directory we discovered that WooCommerce.com expects the directory path to be passed in with the `wccom-back` param for in app purchase URLs.

**E.g. if the back URL is `http://example.org/store/wp-admin/`**
`wccom-site` must equal `http://example.org/store/`
`wccom-back` must equal `/store/wp-admin/`

Please see issue for info.

### CODE REVIEW

**Comment by danielbitzer** [comment]
Yep I'm happy to move it there. However, it's worth noting that onboarding could also use this function. 

See: https://github.com/woocommerce/woocommerce-admin/blob/a021223f24ac80c226d3fd06b77a9189785860dc/client/dashboard/components/cart-modal.js#L51-L61

The only reason I didn't update the onboading code to use `getInAppPurchaseUrl()` in this PR was I couldn't see how this is actually being used on the WooCommerce.com side.

**Comment by psealock** [comment]
>However, it's worth noting that onboarding could also use this function.

Oh right, makes sense where it is then.

>I couldn't see how this is actually being used on the WooCommerce.com side.

Theres a connect to woo.com function if you go through the OBW and select a paid extension. After the profiler this modal pops up and you can connect to woocommerce.com. See https://github.com/woocommerce/woocommerce-admin/pull/3472

**Comment by jconroy** [comment]
@psealock @danielbitzer just thought I'd check in to see how this is looking - seems like we just need the ✅

**Comment by danielbitzer** [comment]
I've just updated the onboarding `CartModel` component to use the new helper method added in this PR. See 81485781414f085f65c7ce4a695130ad8c7fb40d

Should be good to go now.

**Comment by jconroy** [comment]
Looks like a linting issue popped up

```
/home/travis/build/woocommerce/woocommerce-admin/client/dashboard/components/cart-modal.js

  8:10  error  'addQueryArgs' is defined but never used  no-unused-vars

/home/travis/build/woocommerce/woocommerce-admin/client/lib/in-app-purchase.js

  16:0  warning  Missing JSDoc @return description  jsdoc/require-returns-description
```

I'll see if I can get a chance to clean up later today

**Comment by jconroy** [comment]
Pushed up 1d0a46c and 2a021d5 to fix the linting issues

**Comment by danielbitzer** [comment]
@jconroy and I thought one final change was needed on this PR. The `connectNonce` setting was previously added in the marketing feature but now this should be a global setting since it's being used by both onboarding and marketing. This was updated in: 08def0c0353ba8708d9582fcd9ef487dd208c050

**Pull request merged**
