### PR TITLE
Onboarding: Create homepage without redirect

### LINKED ISSUE #3708: Onboarding - customize appearance: remove redirect to edit the homepage post
A significant % of users are dropping in this task after being redirected to edit the homepage post. So as a workaround we should allow them to create a homepage, as it is right now, but keep them in the task instead of redirecting them to the post editor.

We also need to add an event tracking to the new snackbar that displays the link to customize the homepage. It should be triggered when the user clicks to customize: wcadmin_tasklist_appearance_customize_homepage

A detailed explanation of this change is available [here](https://www.figma.com/file/nzAjPR4nqdJTDxH32PT4Qg/On-boarding?node-id=4%3A5728).

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #3708 

* Creates a published homepage on click in the task list.
* Adds a link to edit the homepage in the notice.
* Updates the homepage notice to continue working on post update.

### Screenshots
Screen Shot 2020-02-17 at 7 56 33 PM
Screen Shot 2020-02-17 at 7 54 46 PM

### Detailed test instructions:

1. Delete any homepages created by the onboarding task list.
1. Enable the onboarding task list and visit the Customize Appearance task.
1. Click "Create homepage"
1. Make sure a success notice is shown with the link to edit the hompeage and you are not redirected.
1. Click "Customize" in the notice to edit the homepage.
1. Make an edit and click "Update."
1. Check that the homepage notice and action link to return to the task list is shown.

### CODE REVIEW

**Comment by jeffstieler** [comment]
@pmcpinto updated the original issue to include adding tracking to the snackbar click. It should fire a `tasklist_appearance_customize_homepage` event: https://github.com/woocommerce/woocommerce-admin/issues/3708#issuecomment-587021826

**Comment by pmcpinto** [comment]
> @pmcpinto updated the original issue to include adding tracking to the snackbar click. It should fire a tasklist_appearance_customize_homepage event: #3708 (comment)

Great, thanks @jeffstieler

**Comment by jeffstieler** [comment]
I encountered the following warning during testing: `PHP Warning:  Illegal offset type in isset or empty in /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-admin/src/API/OnboardingTasks.php on line 350`

**Comment by joshuatf** [comment]
@jeffstieler I was unable to reproduce the error.  Do you have steps to recreate it?

Is it possibly something related to the sideload images PR?

**Comment by jeffstieler** [comment]
Also - should the base branch here be `version/1.0`?

**Pull request merged**
