### PR TITLE
Increase chart selection to 10 and allow color overriding

### PR DESCRIPTION
**Pull request by bgrgicak**
Chart colors are currently limited to five colors, this makes it hard to use charts in custom reports.

To improve chart colors this PR increases the limit of max chart items from five to ten and adds additional colors.

To allow developers to use custom chart colors this PR introduces a new filter to allow overriding the existing color pallet.

### Screenshots

Screen Shot 2022-02-04 at 13 05 20
Screen Shot 2022-02-04 at 13 05 05

#### Test new colors
-   Run `npm run storybook`
-  Open the [chart component story](http://192.168.0.16:6007/?path=/story/woocommerce-admin-components-chart--default)
- See the new colors

#### Test color filter
- Add the following JS to your admin head. You can use a plugin like "Add Admin Javascript" to do this:
```
 addFilter( 'woocommerce_admin_chart_item_color', 'example', ( index, key, orderedKeys ) => '#7f54b3' );
```
- Navigate to the profile wizard. `wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fproducts`.
- Make sure the chart line colors are purple.

### CODE REVIEW

**Comment by bgrgicak** [comment]
I just realized that I should have submitted this PR from a fork.
Please let me know if I need to close this PR and resubmit it, if no, I will make sure to use my fork for development next time.

**Review by louwie17 — CHANGES_REQUESTED** [review]
Hi @bgrgicak, thanks for addition to the Chart component and sorry for the delay in reviewing this (we usually add the "needs review" label one's it's ready, but that is not made clear in our contribution docs I noticed and might be up to our porter).

I did leave a couple small suggestions, but outside of that the changes look great and I like the addition of the new filter 💯 
After those two comments are addressed this will be good to merge 😄

**Review by louwie17 — APPROVED** [review]
Thanks for the updates @bgrgicak, the changes look good, you got my approval ✔️ :shipit: 

Feel free to merge it yourself.

**Comment by bgrgicak** [comment]
@louwie17 this is my first change to WC Admin. Is it ok if I merge this PR (I have merge permissions), or is this something someone else needs to do?

**Comment by louwie17** [comment]
> @louwie17 this is my first change to WC Admin. Is it ok if I merge this PR (I have merge permissions), or is this something someone else needs to do?

I can merge it in that case as the first one, but going forward if you have other PRs feel free to merge them yourself once they are approved and have the 'ready to merge' label.

**Comment by moon0326** [comment]
Hi @bgrgicak ✋ 

I know this is already merged, but we received a bug [report](https://github.com/woocommerce/woocommerce-admin/issues/8413) from GlobalStep. It looks like this [line](https://github.com/woocommerce/woocommerce-admin/pull/8258/files#diff-d5046d8bdcb0278dcd1c8880a26182d94ff793c5d2f6f5f40bf20d47f3d23b02R169) introduced the bug. Could you tell me where this CSS is applied to? I'm trying to see if we can remove it.

**Comment by bgrgicak** [comment]
I've seen and fixed this on WCCOM, but didn't know that it was coming from this PR.
I can work on a fix this week.

**Pull request merged**
