### PR TITLE
Update style on shipping banner

### LINKED ISSUE #4938: [WC 4.4 beta1] Create shipping label notice layout is a bit cramped
**Describe the bug**

The message, the `Create shipping label` button and the close icon of the `Create shipping label` notice on the order page feel a bit cramped:

services

**To Reproduce**
I tested using WooCommerce 4.4 beta1 and WordPress 5.5-RC1-48681. 

1. Start OBW.
2. Enter the US address in the `Store details` section during OBW. 
3. On the `Tell us about your business` page, select checkbox next to `Install recommended free business features` so that WC Services could be installed. 
4. Complete OBW.
5. Place an order on the site. 
6. Navigate to the order page and see the notice letting you know that you can create a shipping label with the cramped layout. 

**Expected behavior**
I think more space (padding) between the text, button, and the exit icon will make it for a nicer experience. Alternatively, the `Create shipping label` button can be placed under the message and centered. 

**Screenshots**
N/A

**Desktop (please complete the following information):**

OS: macOS Catalina 10.15.5
Browser: Chrome 84.0.4147.89 (Official Build) (64-bit)

**Additional context**
This was created in WooCommerce Service repo, please refer to the  comments in here: https://github.com/Automattic/woocommerce-services/issues/2106#issuecomment-669214992

### PR DESCRIPTION
**Pull request by harriswong**
Fixes #4938, https://github.com/Automattic/woocommerce-services/issues/2106

Fix the button style in shipping banner after wordpress component upgrade. 

### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Screenshots
The shipping banner button should no longer cover the "x" and pad nicely on the right of the text.
image
image
image
image
image

### Detailed test instructions:

1. Have shipping banner show up. I did this by going to [src/Features/ShippingLabelBannerDisplayRules.php](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/ShippingLabelBannerDisplayRules.php#L102)  and replace this line to `return true || $this->banner_not_dismissed() &&` to force banner to show.
2. Make sure the banner doesn't look like the screenshot described in https://github.com/Automattic/woocommerce-services/issues/2106#issue-668163737

### Notes
The original ticket was created in WooCommerce Service issue https://github.com/Automattic/woocommerce-services/issues/2106 and the conversation was left there.

### CODE REVIEW

**Comment by harriswong** [comment]
@c-shultz is afk until Monday. On my localhost, I was testing it against 4.3.1, so 4.3.2 would be nice I think.

**Comment by c-shultz** [comment]
@timmyc, it was looking a little ugly without this fix, so it would be nice to get it in sooner (especially since it's just some CSS tweaks) if that's not going to disrupt your pipeline too much.

**Comment by timmyc** [comment]
I will cherry pick this in to the 1.4/4.4 release.

**Comment by timmyc** [comment]
Cherry picked to `release/1.4.0` in 1e88884040d28a1179f9e629d8cbaca18753906c

**Comment by becdetat** [comment]
Don't need to cherry pick this to `release/1.5.0-beta.2` as it is already in beta 1 🐴

**Pull request merged**
