### PR TITLE
Get currency from `CurrencyContext`

### LINKED ISSUE #5750: Setup Wizard: Currency symbols and formats not updated for other locales
**Describe the bug**
While currency values change correctly for certain countries (Germany, the United Kingdom), the currency symbol for other countries isn’t updated. For example: The Japanese Yen currency symbol doesn’t show– it only shows the dollar–when selecting Japan (tried Osaka and Tokyo). Similar behavior is observed for South Korea, China, etc. However, we do support them in the Currency options area under settings:

image

**To Reproduce**

1. Go to the 'Store Details' step in the Setup Wizard.
2. Select a country such as Japan, South Korea, or China.
3. Continue the setup to the Business Details section.
4. Select that you are currently selling elsewhere (any of the positive options)
5. Note the "current annual revenue" is still shown with the `$`.
6. Switch to the UK or Germany and note that the currency symbol changes, to the Pound Sterling (£) and Euro (€) respectively. Additionally, the formatting changes, with 2.000,000 instead of 2,000.00 for the Euro, for example.

**Expected behavior**
Currency formatting and symbol should reflect the primary currency used in the country.

**Screenshots**

Screen Shot 2020-11-26 at 1 50 29 PM

**Desktop (please complete the following information):**

* OS: macOS Big Sur
* Browser FireFox, Chrome
* Version 83.0, 86

### PR DESCRIPTION
**Pull request by hsingyuc**
Fixes #5750 

Get currency from `CurrencyContext`.

### Screenshots
螢幕快照 2021-03-31 下午5 52 36

螢幕快照 2021-03-31 下午5 53 16

### Detailed test instructions:
1. Go to WooCommerce home and click the store details
2. Set the country to Japan and continue to Business details
3. Set currently selling on another platform
4. See that the current annual revenue dropdown menu currency match the selected country

### CODE REVIEW

**Comment by moon0326** [comment]
@hsingyuc Thank you for putting this together 👍 

It tested well when I selected Japan as my country, but selecting China or Korea did not work as expected.

China: https://d.pr/i/NmzTiH (notice currency is still displayed in $)
Korea: https://d.pr/i/4aFqlJ (notice the symbol is on the right side. It should be on the left side)

I haven't looked into the root cause yet, but I think these are probably config issues. I can look into that later this week.

I think we should put this PR on hold until then. What do you think?

**Review by joshuatf — COMMENTED** [review]
>China: https://d.pr/i/NmzTiH (notice currency is still displayed in $)

The `localeInfo` only contains some countries.  Long-term we need an API to fetch this data instead of preloading everything since preloading all country data would not be ideal.

>Korea: https://d.pr/i/4aFqlJ (notice the symbol is on the right side. It should be on the left side)

Ah yes, the infamous Los Angeles, Korea 😄 .  For some reason locale info in WooCommerce for `KR` has `currency_pos` as `right`.  May be an issue we need to fix upstream in core.

I'm inclined to give this a ✅  as I think some of these issues are pre-existing with how we load data.  What do you think @moon0326?

**Comment by moon0326** [comment]
> > China: https://d.pr/i/NmzTiH (notice currency is still displayed in $)
> 
> The `localeInfo` only contains some countries. Long-term we need an API to fetch this data instead of preloading everything since preloading all country data would not be ideal.
> 
> > Korea: https://d.pr/i/4aFqlJ (notice the symbol is on the right side. It should be on the left side)
> 
> Ah yes, the infamous Los Angeles, Korea 😄 . For some reason locale info in WooCommerce for `KR` has `currency_pos` as `right`. May be an issue we need to fix upstream in core.
> 
> I'm inclined to give this a ✅ as I think some of these issues are pre-existing with how we load data. What do you think @moon0326?

Yup, I think we can 🚢  it. I will create issues for the other two issues 👍

**Review by moon0326 — APPROVED** [review]
@hsingyuc  Thank you for the change 👍 It looks good and tested well 🚢

**Pull request merged**
