### PR TITLE
Replace marketing extension - Google Listings and Ads

### PR DESCRIPTION
**Pull request by mikkamp**
Fixes 5-gh-woocommerce/google-listings-and-ads

This PR replaces the previous Google Ads extension with the Google Listings and Ads extension.

### Testing instructions
View the installed marketing extensions section on the page Marketing > Overview 
The extension should appear in the following states:

1. Extension not installed (should not be included in the list, if the list is empty this section won't show at all)
image

2. Extension installed but not activated (click activate to confirm it works)
image

3. Extension installed and activated but not setup yet (click "Finish setup" to confirm we get redirected to the get started page)
image

4. Extension installed, activated and setup (click settings to confirm we get redirected to the settings page)
image

Note: The documentation link is not active yet (still in draft)

#### Test onboarding
1. Make sure the extension is installed but not activated
2. [Reset](https://github.com/woocommerce/woocommerce-admin/wiki/Common-Issues#reset-the-onboarding-wizard) the onboarding wizard, and go to `wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard`
3. Go through all the onboarding steps till we reach `Included business features`
4. Ensure the plugin shows up correctly with the right naming and select it as the only extension to add
image
5. Continue and confirm the `plugins were successfully activated` notice shows up
6. Finish onboarding and confirm that the extension was actually activated

Note: Ideally we should test the same onboarding flow, without the extension installed, however at the moment the extension with slug `google-listings-and-ads` is not live on WordPress.org yet (review process is still pending).

#### Test old note removal
If you do not currently have the old note on your WooCommerce Admin home screen, you can add a test note with the correct name as follows:
1. install the WooCommerce Admin Test Helper plugin [here](https://github.com/woocommerce/woocommerce-admin-test-helper)
2. Go to the Admin notes tab
3. Add an admin note with the name `wc-admin-google-ads-and-marketing`
4. Go to the WCA home screen and verify that your test note is present

The note is removed on a new version install, so either install an old version of WCA and upgrade to the current one, or trigger the install process manually:
1. install the WCA test helper
2. go to the Tools tab
3. click the `Trigger WCA install` button

### Changelog note
- Update: Replace marketing extension - Google Listings and Ads.

### CODE REVIEW

**Review by layoutd — APPROVED** [review]
LGTM, relatively minor changes and all testing instructions worked well.

I guess the translation of the `Drive traffic to your store with...` string will be updated during the release process.

**Comment by mikkamp** [comment]
> I guess the translation of the Drive traffic to your store with... string will be updated during the release process.

As far as I can see that would be the case, although I'm not totally sure on how that's run, since it's both a plugin and packages to be included in core.

**Review by timmyc — DISMISSED** [review]
Thanks for the PR @mikkamp - since this PR is removing an existing inbox notification, we should probably add the old note name to [the obsolete note array](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Install.php#L505-L515) and revise the testing instructions on this PR to cover the use case of someone having the old note present in their DB, and the class removal in this PR not impacting things.

In #6510 you can see some testing instructions on how we have handled that with other note removals.

**Comment by mikkamp** [comment]
Thanks @timmyc for the suggestion, @jconroy had already mentioned something about this, so I had tested the scenario but the note action didn't cause any failures, so I left it. It's much nicer to clean up the note though.
Updated the code and the test instructions. It's ready for another round of review.

**Review by joshuatf — APPROVED** [review]
Changes here look good.  Ran through this with and without the note.

Had trouble fully testing the plugin since it's not available WP.org, but hacking around it a bit it's still testing well and I don't see a reason it wouldn't work when it becomes available.

Thanks for the changes, @mikkamp!

**Comment by jconroy** [comment]
Thanks @joshuatf 🙏

**Comment by timmyc** [comment]
cherry picked to `release/2.3.0` in 0749d03aad2c289f08019be8e0bc76222980b3ae

**Pull request merged**
