### PR TITLE
Load the page controller functions file first to prevent fatal errors when disabling WooCommerce Admin

### LINKED ISSUE #6673: Add Task example causes fatal error when WC Admin disabled
**Describe the bug**

In PR #6563 it was identified that example code for the [Setup Tasks](https://developer.woocommerce.com/2021/02/26/use-setup-tasks-to-provide-a-first-class-on-boarding-experience-for-merchants/) documentation causes a fatal error when WooCommerce Admin is disabled with `add_filter( 'woocommerce_admin_disabled', '__return_true' );`

A workaround was added in PR #6563, however this won't resolve the issue until the change lands in core 5.3, scheduled for May. 

**To Reproduce**

With WC Admin bundled with WooCommerce

2. Disable WC Admin with `add_filter( 'woocommerce_admin_disabled', '__return_true' );`
3. Add the [example plugin](https://github.com/woocommerce/woocommerce-admin/blob/main/docs/examples/extensions/add-task/woocommerce-admin-add-task-example.php) linked to in the documentation.
4. See fatal error

**Expected behavior**

Example plugin should check if WC Admin is active, perhaps with `WC()->is_wc_admin_active()`.

### PR DESCRIPTION
**Pull request by hsingyuc**
Fixes #6673 

Load the page controller functions file first to prevent fatal errors when disabling WooCommerce Admin.

Also noted this issue with WC Pay active, but this PR does not address that issue (https://github.com/woocommerce/woocommerce-admin/issues/6703)

### Detailed test instructions:

1. Deactivate WC Admin plugin
1. Checkout this branch and symlink to `woocommerce/packages/woocommerce-admin`
1. Under wp-content create mu-plugins/my-plugin.php
1. Disable WC Admin with add_filter( 'woocommerce_admin_disabled', '__return_true' ); in your my-plugin.php file
1. Add the example plugin linked to by run npm run example -- --ext=add-task
1. Activate the plugin
1. Don’t see the fatal error

### CODE REVIEW

**Comment by ilyasfoo** [comment]
Hi @hsingyuc, I have tested this branch with the test instructions given. However, I still get a fatal.

```
[12-Apr-2021 05:20:50 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Automattic\WooCommerce\Admin\wc_admin_is_registered_page() in /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Loader.php:830
Stack trace:
#0 /var/www/html/wp-content/plugins/add-task/woocommerce-admin-add-task-example.php(17): Automattic\WooCommerce\Admin\Loader::is_admin_page()
#1 /var/www/html/wp-includes/class-wp-hook.php(292): add_task_register_script()
#2 /var/www/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#3 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action()
#4 /var/www/html/wp-admin/admin-header.php(102): do_action()
#5 /var/www/html/wp-admin/plugins.php(603): require_once('/var/www/html/w...')
#6 {main}
  thrown in /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Loader.php on line 830
```

These are my plugins:
```
+-------------------------------+----------+-----------+-------------+
| name                          | status   | update    | version     |
+-------------------------------+----------+-----------+-------------+
| akismet                       | inactive | none      | 4.1.9       |
| hello                         | inactive | none      | 1.7.2       |
| beta                          | inactive | none      | 2.4.7-alpha |
| jetpack                       | active   | available | 9.6-alpha   |
| debug-helper                  | inactive | none      | 1.0.2-alpha |
| woocommerce                   | active   | available | 5.1.0-dev   |
| woocommerce-admin             | inactive | available | 2.1.0-dev   |
| add-task                      | active   | none      |             |
| woocommerce-payments          | inactive | available | 2.1.1       |
| debug                         | must-use | none      | 1.0         |
| connection-ui-activator       | must-use | none      | 1.0         |
| avoid-plugin-deletion         | must-use | none      | 2.0         |
| fix-monorepo-plugins-url      | must-use | none      | 1.0         |
| lolplugin                     | must-use | none      |             |
| userless-connection-activator | must-use | none      | 1.0         |
| wpcomsh                       | must-use | none      |             |
+-------------------------------+----------+-----------+-------------+
```

**Comment by hsingyuc** [comment]
>Also noted this issue with WC Pay active, but this PR does not address that issue (#6703)

@ilyasfoo  Thanks for the review. I also see this issue using WooCommerce Payments; there's a PR to address the issue https://github.com/woocommerce/woocommerce-admin/pull/6771

**Comment by ilyasfoo** [comment]
@hsingyuc Initially I did get an error with WCPay active, but then I've disabled it, and still get an error albeit not from WCPay. You can see in my stack trace that the error thrown by the add-task plugin `/var/www/html/wp-content/plugins/add-task/woocommerce-admin-add-task-example.php(17)`

**Comment by hsingyuc** [comment]
@ilyasfoo  Sorry I missed your WC payments plugin status. The instructions were wrong, this branch should be symlinked to the `woocommerce/packages/woocommerce-admin` directory. I'll update the instructions above. 

FYI, there's also an error of invalid data store; someone is working on it in https://github.com/woocommerce/woocommerce-admin/issues/6703
螢幕快照 2021-04-14 下午8 54 09

**Review by ilyasfoo — APPROVED** [review]
Thanks for clarifying that. I've re-tested and works well. Thank you so much for making this fix! 🚢

**Pull request merged**
