### PR TITLE
Use Composer autoloading for class files

### LINKED ISSUE #2711: Introduce Composer autoloading of classes
Set up Composer autoloading of existing classes, using the `classmap` autoload mechanism.

The intention is to be able to replace the `classmap` with `PSR-4` refactored versions of all of the existing classes.

The PR to resolve this issue should load existing classes in their original locations using a composer generated loader file.

### Additional Info 

https://github.com/woocommerce/woocommerce-admin/issues/2635

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #2711 and #2712.

This PR introduces Composer-based autoloading of class files and updates them to be `PSR-4` compliant.

**Note:** the name change of `WC_Admin_Activity_Panel` to `WC_Admin_Activity_Panels` was done for easier mapping of feature flags to classes, but could be considered to break backwards compatibility. Should that be reworked?

### Detailed test instructions:

- Run `composer install`
- Verify the tests pass
- Smoke test / spot check all functionality in the plugin

### Changelog Note:

I don't think this warrants a changelog entry.

### CODE REVIEW

**Comment by rrennick** [comment]
@jeffstieler This isn't able to find the `WC_Admin_Reports_Sync` class.

**Comment by jeffstieler** [comment]
> This isn't able to find the `WC_Admin_Reports_Sync` class.

Working on it now - we weren't running `composer install` for all PHP versions in CI.

**Comment by jeffstieler** [comment]
@rrennick got the CI build fixed.

**Comment by psealock** [comment]
I'm getting nearly every unit test failing, but its working on CI. I tried re-running the install step, is there anything else?

>the name change of WC_Admin_Activity_Panel to WC_Admin_Activity_Panels was done for easier mapping of feature flags to classes, but could be considered to break backwards compatibility.

By backwards compatibility, you mean if outside code used `WC_Admin_Activity_Panel` it would break, right? If we make a note of it in release notes, it should be ok.

**Comment by jeffstieler** [comment]
> I'm getting nearly every unit test failing, but its working on CI. I tried re-running the install step, is there anything else?

Which PHP version are you using to run tests? It passes for me locally using 7.3.

> By backwards compatibility, you mean if outside code used `WC_Admin_Activity_Panel` it would break, right? If we make a note of it in release notes, it should be ok.

Yes, exactly that.

**Comment by rrennick** [comment]
> Which PHP version are you using to run tests? It passes for me locally using 7.3.

My command line is running 7.1.23. I'm getting the same results as @psealock .

**Comment by jeffstieler** [comment]
Sorry, I misspoke - my VM is running PHP 7.2.18, however, I'm running `composer install` on my host machine which is using PHP 7.3.7.

What are the errors you're getting on 7.1.x?

**Comment by rrennick** [comment]
This looks like the WC rest API may not be initializing correctly:

```
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Installing woocommerce-admin...
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.23
Configuration: /wp-content/plugins/woocommerce-admin/phpunit.xml.dist

EEEEEEEEEEEEEEFFFEFFEFFFEFFEEE.FFFFEFFFEFFFFEFEFFFEF.FFFFF.FFFE  63 / 179 ( 35%)
FEFFFFFFFFEFFEFEFFFFF..............FFFEFFFEFFFFEEFFFEFFFFEFFFEF 126 / 179 ( 70%)
FFEFFFEFFFEFFFFFFEFFFFEFFE.....FFFFFFFFFFFFFFFFFFFFF.           179 / 179 (100%)

Time: 52.81 seconds, Memory: 162.00MB

There were 43 errors:

1) WC_Tests_API_Init::test_order_sync_retries_on_failure
Error: Call to undefined method WC_Order::get_report_customer_id()

/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php:457
/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php:429
/wp-content/plugins/woocommerce-admin/includes/class-wc-admin-reports-sync.php:457
/wp-content/plugins/woocommerce-admin/tests/api-init.php:75
```

**Comment by jeffstieler** [comment]
> `Error: Call to undefined method WC_Order::get_report_customer_id()`

Looks like the `WC_Admin_Order` class isn't being swapped in - is it in your composer classmap? - `vendor/composer/autoload_classmap.php` ?

**Comment by rrennick** [comment]
> is it in your composer classmap?

`572:    'WC_Admin_Order' => $baseDir . '/includes/class-wc-admin-order.php',`

**Comment by rrennick** [comment]
I added a `print_r( get_class( $order ) )` to the unit test and got

```
EWC_OrderEEEEEEEEEEEEEFFFEFFEFFFEFFEWC_Order_RefundEE.FFFFEFFFEFFFFEFEFFFEF.FFFFF.FFFE  63 / 179 ( 35%)
FEFFFFFFFFEFFEFEFFFFF..............FFFEFFFEFFFFEEFFFEFFFFEFFFEF 126 / 179 ( 70%)
FFEFFFEFFFEFFFFFFEFFFFEFFE.....FFFFFFFFFFFFFFFFFFFFF.           179 / 179 (100%)
```

The `get_report_customer_id ` is a `WC_Admin_Order` function.

**Comment by jeffstieler** [comment]
I think I'll leave this open to collect all the PSR-4 work into one branch that can be tested completely and discussed (pertaining to structure) before merge.

**Comment by rrennick** [comment]
> I'm curious if anyone else is experiencing this and a testing environment reset will be needed.

I was still seeing this this morning. I re-installed the test environment `bin/install-wp-tests.sh` and the tests all pass. I expect there is a change in one of the supporting test libraries (WC or WP) that is needed for the test to run.

@jeffstieler The app worked well for me too.

**Comment by jeffstieler** [comment]
@rrennick ready to merge then?

**Comment by rrennick** [comment]
> ready to merge then?

:shipit:

**Pull request merged**
