### PR TITLE
Small documentation fix

### PR DESCRIPTION
**Pull request by ribaricplusplus**
The Screen singleton instance should probably be documented as Screen type.

I understand this is not very relevant, but I'm just learning the codebase and I submit small things I notice. If you don't like these types of pull requests, do tell me.

### CODE REVIEW

**Review by samueljseay — APPROVED** [review]
Looks good to me and thank you for correcting the documentation, its appreciated! 🚀

**Comment by samueljseay** [comment]
@ribaricplusplus Oh just one thing, we just migrated to github actions so you'll need to rebase your PR against latest main to get the checks passing.

**Comment by ribaricplusplus** [comment]
Nice to know that you accept these small fixes. I've rebased the PR.

**Comment by ribaricplusplus** [comment]
Hmm, tests fail for unrelated reasons, is this expected?

**Comment by adrianduffell** [comment]
@ribaricplusplus thanks for rebasing the PR and your work here. We have the tests passing now so I've merged it.

**Pull request merged**
