### PR TITLE
Deleting unneeded double spaces in text strings.

### PR DESCRIPTION
**Pull request by NekoJonez**
Fixes #https://github.com/woocommerce/woocommerce/issues/30486

Deleting unneeded double spaces in text strings.

### CODE REVIEW

**Review by joshuatf — APPROVED** [review]
Thanks for the fix, @NekoJonez!  Checked for additional cases using the regex:
```
(__\(\s['|"|`]).*\s\s+.*(\))
```
 and did not find any.  LGTM 🚢

**Comment by joshuatf** [comment]
@NekoJonez Would you mind adding a changelog entry for this PR?  You can run `npm run changelogger -- add` and then enter:

1. `patch`
2. 4 - Tweak
3. `Delete unneeded double spaces in text strings. #7502`

Thanks!

**Comment by NekoJonez** [comment]
> @NekoJonez Would you mind adding a changelog entry for this PR?  You can run `npm run changelogger -- add` and then enter:
> 
> 1. `patch`
> 2. `4` - Tweak
> 3. `Delete unneeded double spaces in text strings. #7502`
> 
> Thanks!

Can I do that via the browser? Or should I open a powershell or something for that?

**Comment by joshuatf** [comment]
@NekoJonez If you open the `woocommerce-admin` directory you cloned in git, you can run the command from a terminal/shell.

That will create a file and you can commit and push that file to here.

**Comment by NekoJonez** [comment]
> @NekoJonez If you open the `woocommerce-admin` directory you cloned in git, you can run the command from a terminal/shell.
> 
> That will create a file and you can commit and push that file to here.

I never worked via git... I did it all in the browser. :/ So, that's most likely the reason you are loosing me. 
I tried to install github cli but I'm quickly loosing my way in it. 

I'm sorry but the hassle but feel free to either add the changelog entry yourself or I'm totally willing to be guided through it via here/Discord or whatever works the easiest. 
Sorry the inconvience but I'm still learning how Github and such works.

**Comment by joshuatf** [comment]
@NekoJonez We don't have permission to push to your forked repo, so adding this on our end can be a bit challenging.

If you're capable of adding files via the browser, please add a file titled `update-7502` under the `changelogs/` folder with the following text:

```
Significance: patch
Type: Tweak

Delete unneeded double spaces in text strings. #7502

```

**Comment by NekoJonez** [comment]
> Significance: patch
> Type: Tweak
> 
> Delete unneeded double spaces in text strings. #7502

Consider it done

**Comment by joshuatf** [comment]
Thanks, @NekoJonez!

**Pull request merged**
