### PR TITLE
add REST routes for customers, handler for single customer

### LINKED ISSUE #2781: customers endpoint provides invalid customer URL
**Describe the bug**
Original report: https://github.com/woocommerce/woocommerce-rest-api/issues/22

Inconsistent results on `v4/customers` and `v4/customers/{userid}`. This would be addressed by bringing in the WC REST API as a package and implementing the `v4` endpoints.

**To Reproduce**

1. Activate WooCommerce only
2. Load `/wp-json/wc/v4/customers`

```
{
  "code": "rest_no_route",
  "message": "No route was found matching the URL and request method",
  "data": {
    "status": 404
  }
}
```

3. Activate `woocommerce-rest-api`
4. Load `/wp-json/wc/v4/customers`

```
[
  {
    "id": 51,
    "date_created": "2019-07-08T14:51:49",
    "date_created_gmt": "2019-07-08T17:51:49",
    "date_modified": "2019-07-08T14:52:27",
    "date_modified_gmt": "2019-07-08T17:52:27",
    "email": "holden25@example.org",
    "first_name": "Abbigail",
    "last_name": "Batz",
    "role": "customer",
    "username": "macejkovic.noble",
    "billing": {
...
    },
    "shipping": {
...
    },
    "is_paying_customer": true,
    "avatar_url": "https://secure.gravatar.com/avatar/cd2a899ae34ec17a2ab22e2ee60bd8ec?s=96&d=mm&r=g",
    "meta_data": [
      {
        "id": 2131,
        "key": "wc_last_active",
        "value": "1562544000"
      }
    ],
    "_links": {
      "self": [
        {
          "href": "https://ron.localhost/wp-json/wc/v4/customers/51"
        }
      ],
      "collection": [
        {
          "href": "https://ron.localhost/wp-json/wc/v4/customers"
        }
      ]
    }
  },
```

5. Activate `woocommerce-admin`
6. Load `/wp-json/wc/v4/customers`

```
[
  {
    "id": 51,
    "date_created": "2019-07-08T14:51:49",
    "date_created_gmt": "2019-07-08T17:51:49",
    "date_modified": "2019-07-08T14:52:27",
    "date_modified_gmt": "2019-07-08T17:52:27",
    "email": "holden25@example.org",
    "first_name": "Abbigail",
    "last_name": "Batz",
    "role": "customer",
    "username": "macejkovic.noble",
    "billing": {
...
    },
    "shipping": {
...
    },
    "is_paying_customer": true,
    "avatar_url": "https://secure.gravatar.com/avatar/cd2a899ae34ec17a2ab22e2ee60bd8ec?s=96&d=mm&r=g",
    "meta_data": [
      {
        "id": 2131,
        "key": "wc_last_active",
        "value": "1562544000"
      }
    ],
    "_links": {
      "self": [
        {
          "href": "https://ron.localhost/wp-json/wc/v4/customers/51"
        }
      ],
      "collection": [
        {
          "href": "https://ron.localhost/wp-json/wc/v4/customers"
        }
      ]
    }
  },
```
7. Deactivate `woocommerce-rest-api`
8. Load `/wp-json/wc/v4/customers` (different order)

```
[
  {
    "id": 137,
    "user_id": 141,
    "username": "ekuhlman",
    "name": "Simone Ortiz",
    "email": "frankie39@example.com",
    "country": "LV",
    "city": "Veumbury",
    "state": "NY",
    "postcode": "24473",
    "date_registered": "2019-07-08T14:55:30",
    "date_last_active": "-0001-11-29T19:45:36",
    "orders_count": 0,
    "total_spend": 0,
    "avg_order_value": 0,
    "date_last_order": null,
    "date_registered_gmt": "2019-07-08T17:55:30",
    "date_last_active_gmt": "-0001-11-30T00:00:00",
    "_links": {
      "customer": [
        {
          "href": "https://ron.localhost/wp-json/wc/v4/customers/141"
        }
      ]
    }
  },
```

9. Repeat with customer URL `https://ron.localhost/wp-json/wc/v4/customers/51`

REST API active - data is the same as the collection endpoint
WC Admin without REST API active is a 404

**Expected behavior**
- The single customer endpoint should exist without the REST API plugin being active
- WC Admin implementation of the `customers` endpoint should deliver the same as or a superset of the REST API endpoint.

### PR DESCRIPTION
**Pull request by rrennick**
Fixes #2781

This PR registers both the `/wc-analytics/customers` and `/wc-analytics/customers/{id}` end points. The existing implementation replaced the `/wc-analytics/customers` end point handler.

This is related to both #2809 and #2181. The WC Admin customer `id` is a different value than the WC REST API customer `id`. This PR does not attempt to address this difference.

Discussion: Should this PR include `previous` and `next` links?

### Detailed test instructions:

- In a REST client load `/wc-analytics/customers`. Use `per_page` & `page` to fetch any customer set.
- In a REST client load `/wc-analytics/customers/{id}` using `id`s from previous step
- In your dashboard, clear WC transients
- Test the Analytics -> Customers to ensure the page functions properly.

### Changelog Note:

Fix: Add single customer REST API end point.

### CODE REVIEW

**Comment by rrennick** [comment]
Merge conflicts addressed in this one.

**Comment by jeffstieler** [comment]
`/wc/v4/customers` 404s for me. It looks like the code is registering `wc-analytics/customers`?

**Comment by rrennick** [comment]
> It looks like the code is registering wc-analytics/customers?

@jeffstieler Thanks, yes. I updated the PR description to reflect the correct endpoints from #3204.

**Comment by jeffstieler** [comment]
> The WC Admin customer id is a different value than the WC REST API customer id. This PR does not attempt to address this difference.

While it wasn't introduced in this PR, what do you think about fixing the customer `_link` in the response here? It's forming a URL with the `wc-analytics` namespace, but the WP user ID instead of our customer ID (which causes it to 404, or return the wrong customer).

> Discussion: Should this PR include previous and next links?

I don't think so. Previous/Next based on what? There isn't a way to sort results in this endpoint right?

**Comment by rrennick** [comment]
@jeffstieler Nice catch :) Can you have another quick look at this?

> what do you think about fixing the customer _link in the response here?

Fixed in https://github.com/woocommerce/woocommerce-admin/pull/3174/commits/d8b2ceaff0695d4468821fb2787ff71ac7907015

> Should this PR include previous and next links?

Added a `collection` link for consistency with other end points.

**Comment by jeffstieler** [comment]
Looks good @rrennick - 🚢 it!

**Pull request merged**
