### PR TITLE
Image optimization

### PR DESCRIPTION
**Pull request by lowwebtech**
This PR is about image optimization.

1. Paystack image is resized to a more "normal" size
2. PNG image are converted to PNG8 with ImageAlpha and optimized with ImageOptim
3. SVG are optimized with svgo

### Detailed test instructions:

- open images and visually compare without previous version
- there isn't any visible modification of images

No changelog required

### CODE REVIEW

**Review by samueljseay — APPROVED** [review]
Thanks so much for this contribution, it looks good and will have a good impact on the bundle size. 🚀

**Comment by samueljseay** [comment]
@lowwebtech Note that you'll just need to merge latest main to your branch to get e2e to pass. Thanks!

**Comment by lowwebtech** [comment]
Hi @samueljseay 

What do I have to do to complete e2e tests ?
This branch is already up-to-date with latest main.

Thanks

**Comment by samueljseay** [comment]
@lowwebtech your branch is not up to date with latest main (the fix was made after this pr and you haven't rebased or merged main afaict since then), there is a fix there for the failing e2e tests.

The simplest way to do get it up to date is to do something roughly like:

```
git checkout main
git pull origin main
git checkout image_optimization
git merge origin/main
git push origin image_optimization
```

If there are conflicts you'll need to address them. If there is a package-lock conflict the simplest thing is to delete the lock and rerun `npm install` then commit the new lock file.

I'd do it for you, but I am having some trouble with pushing to your branch at the moment.

**Comment by lowwebtech** [comment]
Is it ok now ?

**Comment by samueljseay** [comment]
Thanks @lowwebtech thats great! And thanks again for this contribution!

**Pull request merged**
