### PR TITLE
convert zero last active date to null in customer query

### LINKED ISSUE #2746: Customer Analytics - Last Active coming up as Invalid Date
**Describe the bug**
Customer Analytics Last Active date is coming up as "Invalid Date" for a lot of my customers.

**To Reproduce**
View Customer Analytics

**Expected behavior**
Expected the see a date.

**Screenshots**
I don't think a screen shot would help, but here's the output from my google chrome console.
```
[Violation] Forced reflow while executing JavaScript took 67ms
index.js?ver=0.16.0:14 [Violation] 'setTimeout' handler took 54ms
deluminate.js:379 [Violation] 'DOMContentLoaded' handler took 1118ms
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,jquery-ui-core,jquery-ui-mouse,jquery-ui-resizable,jquery-u&load[]=i-draggable,jquery-ui-button,jquery-ui-dialog&ver=229aef1a9ca4d644f11c41834ea08f47:2 [Violation] 'DOMContentLoaded' handler took 274ms
[Violation] Forced reflow while executing JavaScript took 60ms
moment.min.js?ver=2.22.2:1 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: -0001-11-29T19:00:00, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://www.mysite.com/wp-includes/js/dist/vendor/moment.min.js?ver=2.22.2:1:3368)
    at Yt (https://www.mysite.com/wp-includes/js/dist/vendor/moment.min.js?ver=2.22.2:1:21353)
    at Ot (https://www.mysite.com/wp-includes/js/dist/vendor/moment.min.js?ver=2.22.2:1:22064)
    at Tt (https://www.mysite.com/wp-includes/js/dist/vendor/moment.min.js?ver=2.22.2:1:22146)
    at c (https://www.mysite.com/wp-includes/js/dist/vendor/moment.min.js?ver=2.22.2:1:209)
    at u (https://www.mysite.com/wp-content/plugins/woocommerce-admin/dist/components/index.js?ver=0.16.0:14:67150)
    at Ts (https://www.mysite.com/wp-content/plugins/woocommerce-admin/dist/components/index.js?ver=0.16.0:27:361350)
    at Td (https://www.mysite.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:82:11)
    at hi (https://www.mysite.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:102:385)
    at Qg (https://www.mysite.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:144:217)
```

**Additional context**
I exported the results and those dates are all coming up as "-0001-11-29T19:00:00"

I also increased my view to 100 customers and sorted it. I have 83 customer's with "Invalid Date" listed.

### PR DESCRIPTION
**Pull request by rrennick**
Fixes #2746

This PR converts the customer `date_last_active` to `NULL` when it's a zero date. It also adds a `'—'` placeholder in the customer table when the `date_last_active` is `NULL`.

### Detailed test instructions:

- In the `wp_wc_customer_lookup` table change `date_last_active` to `0000-00-00 00:00:00` on at least one customer
- Load Analytics -> Customers
- Use page navigation to find that customer in the table
- The placeholder should show for the last active date

### Changelog Note:

Fix: Customer last active date showing `Invalid date`.

### CODE REVIEW

**Comment by rrennick** [comment]
Additional question: I found these dates on orders created by wc-smooth-generator. Are `0` last active dates expected?

**Comment by rrennick** [comment]
The unit test on this failed due to an error downloading WP on one of the tests.

**Comment by jeffstieler** [comment]
> The unit test on this failed due to an error downloading WP on one of the tests.

You can restart Travis builds for intermittent failures like this.

Screen Shot 2019-08-08 at 9 11 35 AM

**Comment by jeffstieler** [comment]
I'm still seeing `Invalid date` for customer rows with `0000-00-00 00:00:00` for `date_last_active`.

Changing the SQL IF to `date_last_active <= "0000-00-00 00:00:00"` seems to work though.

**Comment by rrennick** [comment]
@jeffstieler SQL updated in https://github.com/woocommerce/woocommerce-admin/pull/2764/commits/bc394e9a460705160993fcf64e0a7ff5381d6d71

**Pull request merged**
