### PR TITLE
Profile wizard style consistency updates

### PR DESCRIPTION
**Pull request by jameskoster**
Please forgive me @joshuatf. I fixed up the Product Types step but kept finding style issues to fix that spilled into the other steps. It's mostly just a case of utilising the `Text` component where appropriate, replacing color studio vars with core equivalents, and a few spacing tweaks. I hope this isn't too painful to merge 😬

To test: Just work through the Profile Wizard and check for anomalies. I didn't touch anything functional so everything should still work as before.

### CODE REVIEW

**Review by psealock — COMMENTED** [review]
Code looks good, but I'll give final approval to @joshuatf. Since https://github.com/woocommerce/woocommerce-admin/pull/5015 is ready for merge, can you give this a look over and rebase?

**Review by joshuatf — COMMENTED** [review]
Thanks for the changes here, @jameskoster!  This looks good, will just need a rebase since I merged in https://github.com/woocommerce/woocommerce-admin/pull/5015.

`product-types.scss` is now under `product-types/style.scss` so this will probably have a few conflicts to resolve.  If you need any help or want me to take over the rebase, feel free to drop me a line.

**Comment by jameskoster** [comment]
@joshuatf I will most definitely need help with that 😅

**Comment by samueljseay** [comment]
I'll do a rebase

**Comment by samueljseay** [comment]
@jameskoster @joshuatf Please take a look at #5059 and see if it looks good. Thanks 😺

**Pull request closed without merging**
