### PR TITLE
IconButton: Replace with Button

### PR DESCRIPTION
**Pull request by psealock**
Partial fix to https://github.com/woocommerce/woocommerce-admin/issues/4383

Remove use of `IconButton` in favor of just `Button` so we can update `@wordpress/components`.

See [`@wordpress/components` changelog](https://github.com/WordPress/gutenberg/blob/master/packages/components/CHANGELOG.md).

I also removed `SplitButton` component because it wasn't used anywhere.

### Accessibility

- [x] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [x] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [x] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Screenshots

Here are some quick screenshots of updated buttons

Screen Shot 2020-05-22 at 11 18 16 AM
Screen Shot 2020-05-22 at 11 30 09 AM
Screen Shot 2020-05-22 at 11 46 13 AM
Screen Shot 2020-05-22 at 11 54 39 AM
Screen Shot 2020-05-22 at 11 54 50 AM
Screen Shot 2020-05-22 at 11 54 58 AM
Screen Shot 2020-05-22 at 11 55 43 AM
Screen Shot 2020-05-22 at 11 55 48 AM
Screen Shot 2020-05-22 at 11 56 33 AM
Screen Shot 2020-05-22 at 11 58 44 AM
Screen Shot 2020-05-22 at 11 59 21 AM
Screen Shot 2020-05-22 at 11 59 43 AM

### Detailed test instructions:

1. Click around the app, checking elements shown in the screenshot.
2. Double check that colors are correct. In particular the svg color should match the text.

### Changelog Note:

Dev: Remove use of `IconButton` in favor fo `Button`

### CODE REVIEW

**Comment by mattsherman** [comment]
In Analytics / Orders, the X button for filter criteria is misaligned vertically:

Filter criteria X misalignment

**Comment by psealock** [comment]
Thanks for the review @mattsherman !

I added the 8px of padding to the remove button on Advanced Filters like you suggested.

>Things looked okay to me, but then again, I'm color blind. So, I'll leave the color correctness determination to another set of eyes!

I think we should be good here with the rule `.components-button svg { fill: currentColor } `

**Comment by mattsherman** [comment]
@psealock Oops... noticed you snuck the `jest` commit in while I was approving... I grabbed the latest and ran the following to verify the changes from that commit were good.

```
npm test -- -i packages/components/src/search-list-control/test/index.js
```

**Comment by psealock** [comment]
Thanks for the late night review @mattsherman.

I'm in the middle of a multibranch rebase fiasco here. It looks like test fail. Its a jest snapshot error due to props like `isExpanded= { false }` v. `isExpanded= "false"`

**Comment by psealock** [comment]
looks like reverting that last commit did the trick. Maybe it was a dependency thing happening.

**Comment by mattsherman** [comment]
Hrm... but, after running the unit test manually again after your revert, the tests fail, as I would actually expect!

**Comment by psealock** [comment]
So weird! Something is/was off with snapshots. If you were on a different branch and switched to this one without npm install'ing, that may be the issue.

In any case, I feel good about merging this one because tests pass on travis and oddness surrounds known issues.

**Pull request merged**
