### PR TITLE
Add ability to receive an emailed download link to report export endpoint.

### LINKED ISSUE #311: Analytics: CSV Download
68747470733a2f2f6175746f6d61747469632e696e766973696f6e6170702e636f6d2f7374617469632d7369676e65642f6c6976652d656d6265642f3236363e280a6-2018-08-07-11-28-25

Background: p90Yrv-LB-p2

The background thread above contains some excellent discussion on this feature from both a business side, and a technical approach. But I did want to highlight this comment from @warrendholmes which sums up the feature nicely:

> we will move forward with functionality to implement exporting all the data.

This issue will act as a parent issue for child tasks related to the Download CSV functionality.

**Phase 1: Browser-Side Export of data in table**
Since the ability to fully export _all_ data that could be returned by a particular set of filters will require some additional server side work, we would like to implement an interim solution so we can conduct usability tests against the Revenue Report ( and others ) prior to the completion of the back-end logic.

As such, phase one will implement the same approach that exists in both Calypso Stats and legacy WooCommerce reports, where data that is already present in the client will be exported. [Calypso CSV Download](https://github.com/Automattic/wp-calypso/tree/a70587157b33783ba4d5e0e4a1e136680d459d51/client/my-sites/stats/stats-download-csv) is one implementation that can be used as prior art.

- [x] Tracking phase one in #312.

**Phase 2: Server Side Job / Endpoints**
As outlined in the background post, the long-term desired setup for the CSV Download involves the creation of a new API endpoint that will accept arguments of report type ( i.e. Revenue Report ), and any associated filters ( i.e. date ranges, unit/day/week/month ) and enqueue a job to query and persist the data as a csv file. An additional endpoint will allow the client-side logic to query and determine the status of a pending export job, and get the download URL for the file when it is complete.

Prior discussion hinted at possibly being able to leverage Woo's built in digital download support to secure the data file export process.

__Server Tasks__
- [x] Implement Job logic to query large data sets, and save results to the file system
- [x] Create API endpoints to allow queueing a new job, and requesting status of prior jobs
- [x] Implement logic to ensure the serving of the exported data files is secure, and files may only be retrieved by store users with proper permissions
 
__Client Side Tasks__
- [ ] Add new logic to the download CSV button to enqueue an export job if the data set in the report table view exceeds the current default page size. That is, if all data is shown in the current view - continue to use the client-side download built during phase one - otherwise leverage the new server job logic.
- [ ] Implement the download via email link

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #311.

This PR seeks to introduce an `email` parameter to the Report Export REST endpoint. When a boolean `true` is passed to the endpoint, an action is scheduled to email a link to download the report to the requesting user.

### Screenshots:

Screen Shot 2019-09-06 at 10 28 00 AM

### Detailed test instructions:

- `POST /wc/v4/reports/products/export` with body: `{ "email": true }`
- Verify a `woocommerce_admin_email_report_download_link` scheduled action exists (Tools > Scheduled Actions)
- When 100%, verify the email associated with your user account has received an email with a link to download the export
- Verify the download link in the email works

### Changelog Note:

Enhancement: add option to email a download link when exporting reports.

### CODE REVIEW

**Comment by psealock** [comment]
I updated this to "Fixes #311" and broke out the in-browser option to its own issue (https://github.com/woocommerce/woocommerce-admin/issues/2936) along with another issue blocking progress on that, filter notifs by user in https://github.com/woocommerce/woocommerce-admin/issues/2937.

**Comment by psealock** [comment]
How did you set up email with VVV? I exposed my site via ngrok, similar to how I connect to Jetpack, and am waiting for a confirmation email. Would that be sufficient? I'm not seeing it in spam  or inbox. Any suggestions?

**Comment by jeffstieler** [comment]
Go to vvv.test and follow the link to MailHog - VVV catches mail by default
:)

**Comment by jeffstieler** [comment]
Whoops! Looks like I left a test in: https://github.com/woocommerce/woocommerce-admin/pull/2899/files#diff-432e1f268e90545777dd8dcd9b5c5e44R65

**Comment by jeffstieler** [comment]
@psealock fixed in https://github.com/woocommerce/woocommerce-admin/pull/2899/commits/a2666c83748fa240e04144bdf174cd34e1a2a45e.

**Pull request merged**
