### PR TITLE
This fix fixes the bug: "Undefined index: id"

### PR DESCRIPTION
**Pull request by Jazz-Man**
PHP Notice:  Undefined index: id in .../plugins/woocommerce/packages/woocommerce-admin/src/Loader.php on line 1046
ErrorException: Undefined index: value in .../plugins/woocommerce/packages/woocommerce-admin/src/Loader.php:1046
Stack trace:
#0 .../plugins/woocommerce/packages/woocommerce-admin/src/Loader.php(1046): {closure}()
#1 .../wp-includes/class-wp-hook.php(287): Automattic\WooCommerce\Admin\Loader::add_component_settings()
#2 .../wp-includes/plugin.php(212): WP_Hook->apply_filters()
#3 .../plugins/woocommerce/packages/woocommerce-blocks/src/Assets/AssetDataRegistry.php(132): apply_filters()
#4 .../plugins/woocommerce/packages/woocommerce-blocks/src/Assets/AssetDataRegistry.php(223): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->initialize_core_data()
#5 .../wp-includes/class-wp-hook.php(287): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->enqueue_asset_data()
#6 .../wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#7 .../wp-includes/plugin.php(484): WP_Hook->do_action()
#8 .../wp-admin/admin-footer.php(95): do_action()
#9 .../wp-admin/post.php(369): require_once('/var/www/stagin...')
#10 {main}

Fixes #

_Replace this with a good description of your changes & reasoning._

### Accessibility

-   [ ] I've tested using only a keyboard (no mouse)
-   [ ] I've tested using a screen reader
-   [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
-   [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Detailed test instructions:

-   Ex: Open page `url`
-   Click XYZ…

### CODE REVIEW

**Comment by adrianduffell** [comment]
@moon0326 is this a duplicate of https://github.com/woocommerce/woocommerce-admin/pull/5664?

**Comment by samueljseay** [comment]
After some investigation this indeed seems like a dupe of #5664 I'm gonna close this one for now in favour of that fix, but I really appreciate the contribution @Jazz-Man

**Comment by Jazz-Man** [comment]
@samueljseay This problem is still unresolved
https://github.com/woocommerce/woocommerce-admin/pull/7262

**Comment by moon0326** [comment]
@Jazz-Man I left a comment in your PR.

Just out of curiosity, is it possible for you to print out `$group_settings` that is causing the error? I would like to know the cause of this error.

**Pull request closed without merging**
