### PR TITLE
Dep Ext Webpack Plugin: Map wc-navigation to wc-admin

### PR DESCRIPTION
**Pull request by psealock**
Fixes https://github.com/woocommerce/woocommerce-admin/issues/5559

When using SlotFill from `@woocommerce/navigation` a dependency on `wc-admin-app` must be declared. This PR does that which will ultimately also bring in a dependency on `wc-navigation`.

https://github.com/woocommerce/woocommerce-admin/blob/62501ce94073a9646e560bfea7222309a3c5b04f/src/Loader.php#L481-L494

See discussion in https://github.com/WordPress/gutenberg/pull/27020 for previous attempts to solve this one.

### Detailed test instructions:

1. `npm run build`.
2. `cd packages/dependency-extraction-webpack-plugin`.
3. `npm link`
4. `cd ../..`
5. `npm run create-wc-extension`
6. Follow the instructions and name your new app.
7. `cd ../<new app name>`
8. `npm install`
9. `npm link @woocommerce/dependency-extraction-webpack-plugin`
10. `npm start`
11. Add this code to `src/index.js`
```js
import { Table } from '@woocommerce/components';
import { WooNavigationItem } from '@woocommerce/navigation';

console.log( Button, Table, WooNavigationItem );
```
12. Check that `build/index.assets.php` correctly indicates dependencies on `wc-admin-app` and `wc-components`

### CODE REVIEW

**Review by louwie17 — APPROVED** [review]
Looks great, and tested well :) Just had to switch steps 8 and 9 around in testing instructions.

Approving this, but in relation to [this last comment](https://github.com/WordPress/gutenberg/pull/27020#issuecomment-729627352) will navigation always depend on `wc-admin-app`, or could there be exceptions? Where turning it on/off would be needed. My bad if this is a given 🙈

**Comment by psealock** [comment]
Thanks for the review @louwie17 !

@senadir What do you think about this solution? Only `@woocommerce/navigation` is affected.

>If you're going to implement this, I'd prefer if it can be turned off so we can use that package in our code.

I'd rather make a tool useable internally and externally than cater to this scenario. If this change makes too many assumptions to be useable in the case of Blocks, it may be best to communicate this need to extension developers instead. I can also make the dependency explicit in the starter pack. What do you think?

**Comment by senadir** [comment]
Hey, sorry for the late response here.
Taking from this, there's no dependency on `wc-navigation` anymore? This assumes that navigation is only going to be used in the context of wc-admin and that's fine, a custom rule can be written to revert this PR is navigation was used outside wc-admin.

My previous comment on that PR was if any package has `@woocommerce/*` in its name, it would also add `wc-admin-app` as a dependency.
The above seems like a sane workaround that doesn't effect anyone.

**Comment by psealock** [comment]
>Taking from this, there's no dependency on wc-navigation anymore?

There would be because wc-admin has a dependency on `wc-navigation`

>My previous comment on that PR was if any package has @woocommerce/* in its name, it would also add wc-admin-app as a dependency.

This was my original intention with https://github.com/WordPress/gutenberg/pull/27020. I'd add an the option in the constructor of the class extending the original Dep Ext Webpack Plugin. 

>The above seems like a sane workaround that doesn't effect anyone.

I'll try and figure out a new way to make this happen

**Comment by psealock** [comment]
It turns out this is a wc-admin dependencies issue. Here is the fix https://github.com/woocommerce/woocommerce-admin/pull/5722.

This one can be closed out. Thanks for the reviews everyone!

**Pull request closed without merging**
