### PR TITLE
Reset State Between E2E Tests

### PR DESCRIPTION
**Pull request by adrianduffell**
Fixes #

Todo:

- [x] Reset onboarding and onboarding settings
- [ ] Clear specific options (@adrianduffell - reset plugin)
- [x] Reset/clear all notes (@louwie17 close to done)
- [x] Clear transients (@adrianduffell - reset plugin)
- [x] Scheduled tasks?
- [x] Clear products/orders (@louwie17 )
- [ ] Deactivate/remove plugins (@louwie17 )
- [ ] Clear analytics data (might not be needed as long as we run the action scheduler after we clear products and orders)
- [ ] Clear user settings (ex: `woocommerce_meta.dashboard_sections`)

### Accessibility

-   [ ] I've tested using only a keyboard (no mouse)
-   [ ] I've tested using a screen reader
-   [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
-   [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Detailed test instructions:

-   Ex: Open page `url`
-   Click XYZ…

### CODE REVIEW

**Comment by rrennick** [comment]
@adrianduffell I'm not sure what all you might be looking to reset but the lastest version of the `@woocommerce/e2e-utils` has code for resetting for onboarding: https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/utils/src/flows/with-rest-api.js#L48

Although we are missing clearing out a few things the main core E2E is reset in https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/core-tests/specs/activate-and-setup/onboarding-tasklist.test.js#L31:L45.

While working on #6807 I'm hoping to merge the two test suites so we have the combined coverage in the one package.

**Comment by adrianduffell** [comment]
> @adrianduffell I'm not sure what all you might be looking to reset but the lastest version of the `@woocommerce/e2e-utils` has code for resetting for onboarding: https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/utils/src/flows/with-rest-api.js#L48
> 
> Although we are missing clearing out a few things the main core E2E is reset in https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/core-tests/specs/activate-and-setup/onboarding-tasklist.test.js#L31:L45.
> 
> While working on #6807 I'm hoping to merge the two setup/onboarding test suites so we have the combined coverage in the one package.

@rrennick Thanks this is part of the reset plugin we discussed together internally in pcr5Cj-rK-p2. My aim is to have a complete data and state reset function so that the tests can be run in isolation.

I don't want to block your progress on issue #6807. For the onboarding test, I think you could switch over to the `@woocommerce/e2e-utils` reset functions. Perhaps the reset plugin could later be integrated into `@woocommerce/e2e-utils` if it proves to be a success in other features of WC Admin.

The progress of the reset plugin can be seen in the initial PR over here https://github.com/woocommerce/woocommerce-reset/pull/1. Presently, it only deletes the options used by WC Admin but I plan to expand it to reset more items later.

**Comment by rrennick** [comment]
@adrianduffell That sounds good.

**Comment by adrianduffell** [comment]
Just putting this on hold to avoid churn from PR https://github.com/woocommerce/woocommerce-admin/pull/7084. I'll look to return to it in the next cooldown.

**Comment by rrennick** [comment]
@adrianduffell I'm probably going to be 3 weeks before I get back to #7084.

**Comment by adrianduffell** [comment]
No stale. Picking this back up when cooldown starts tomorrow.

**Comment by adrianduffell** [comment]
Hey @louwie17 thanks for picking this up. It's looking good!

Would you like some help with the todo list this cool down? I'll have some availability for it!

**Comment by louwie17** [comment]
> Hey @louwie17 thanks for picking this up. It's looking good!
> 
> Would you like some help with the todo list this cool down? I'll have some availability for it!

Yeah for sure, help would be great, maybe just tag your name beside a todo item, so we know what each other are working on.
I believe a good chunk of the todo's already have bits and pieces in place, but require some extra work for it to be fully done.

I am leaning towards trying to do as much as we can with the http client the `@woocommerce/api` provides, and any items that don't fit in, move them to the reset plugin.

**Comment by adrianduffell** [comment]
> Yeah for sure, help would be great, maybe just tag your name beside a todo item, so we know what each other are working on. I believe a good chunk of the todo's already have bits and pieces in place, but require some extra work for it to be fully done.
> 
> I am leaning towards trying to do as much as we can with the http client the `@woocommerce/api` provides, and any items that don't fit in, move them to the reset plugin.

Sounds good! To avoid committing to this branch and conflicts I could work on the items needing to go in the reset plugin.

I'd like the reset plugin to eventually be capable of resetting all the things but I think I need to plan out what that would look like. I agree on trying to do as much as possible with `@woocommerce/api` right now.

**Comment by adrianduffell** [comment]
I've got a PR for clearing transients over here https://github.com/woocommerce/woocommerce-reset/pull/3

**Pull request closed without merging**
